### ISSUE TITLE
[Feature request]: Add markdown

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodDev/Butterfly#125]

**Comment by Shahin-rmz** [comment]
This one is a must.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This is a brilliant addition, but solely if it is possible to disable. I do not want all of my notes to be interpreted as Markdown.

**Comment by CodeDoctorDE** [comment]
Yeah I want to add three options: simple, markdown and rich text

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@CodeDoctorDE, which format shall “rich text” utilize?

**Comment by CodeDoctorDE** [comment]
I'm not very sure, maybe I will create my own rich text format to have a better support in my app.
But I don't think it will be ever possible to import docs files. The format is very heavy to support.

**Comment by CodeDoctorDE** [comment]
I split the rich text support in a new issue #247.
These are two different features to develop.

**Comment by CodeDoctorDE** [comment]
Related to https://github.com/flutter/flutter/issues/109373.
We need to wait until the issue was closed. I will look to add basic rich text support with #247.

**Comment by CodeDoctorDE** [comment]
I will implement an own renderer in 2.0

**Comment by MrRulf** [comment]
would latex/katex support also be included?

**Comment by CodeDoctorDE** [comment]
Latex is not markdown. Maybe adding an extra text type in https://github.com/LinwoodCloud/Butterfly/issues/97? Or we can add it as a code block
\`\`\`katex
abc
\`\`\`

**Comment by CodeDoctorDE** [comment]
Basic markdown system is implemented.
Advanced features like math rendering will be added later.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-alpha.4
