### ISSUE TITLE
[Feature request]: Embedding to other apps like Jopling?

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodDev/Butterfly#250]
# Help wanted!

```[tasklist]
- [ ] #252
- [ ] #253
```

### Is your feature request related to a problem? Please describe

It can happen, that we need to do note taking, and also write something with pen.
If we can switch from joplin to Butterfly, draw something and comeback, it would be nice.

### Describe your feature request!

I have already talked about this feature.
[This link](https://discourse.joplinapp.org/t/drawing-with-a-pen/69/4) is also talking about that. It would be awesome if we could have embedding Butterfly inside other productivity apps.

### Additional context

my personal wiki is dokuwiki which uses [embedded pen writing](https://www.dokuwiki.org/plugin:drawio). If we could have this feature by Butterfly it would be nice, and the dev does not need to concentrate on features such as markdown or rich text, and can concentrate on enhancing pen experience of the users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Okay...
The embed support is already there: https://docs.butterfly.linwood.dev/embed/intro

But I think it is useful to create the plugin here to have official support.

**Comment by Shahin-rmz** [comment]
Nice, if you know Javascript, I think you can help Joplin, or Qownnotes to embed Butterfly in their app!
I try to talk with the developer of QOwnnotes, as it is written in C++.

**Comment by CodeDoctorDE** [comment]
I will use typescript because it's better for error detection, autocompletion and more.
But for embedding to work, it needs to display a webview to work. If I get it to work it won't be difficult to implement.
I want to have everything on one place.
Because of that I will put all plugin integration in the `plugins` subdirectory (which currently not exist).

**Comment by CodeDoctorDE** [comment]
# Help wanted

I need help to implement the integrations.

Please reply if you can develop:

* Nextcloud integration (PHP): https://docs.nextcloud.com/server/latest/developer_manual/app_development/index.html
* Joplin (TypeScript): https://joplinapp.org/api/get_started/plugins/

Please create your integration in the `integrations` directory, for example `integrations/nextcloud`

**Comment by Shahin-rmz** [comment]
> # Help wanted

I'll try to post the request on the forums of each app, this way you may find a better resources.

**Comment by CodeDoctorDE** [comment]
I will close this issue since we have issues for specific apps.
Embedding support was added, now we need to develop plugins for these apps: https://docs.butterfly.linwood.dev/embed/intro
