### ISSUE TITLE
[Bug]: Created elements appear under other elements

### ISSUE THREAD

**Issue by ProgrammerLP** [LinwoodDev/Butterfly#287]
### What happened?

i drawed something in the web version in firefox, then i zoomed and some lines were deleted. More Information in the Video

https://user-images.githubusercontent.com/101939228/190451843-c3d1d77b-ca89-42a2-90de-e6b96f5a3c15.mp4

### Version

current preview 

### Platform

Web

### Relevant log output

```shell
---
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ProgrammerLP** [comment]
its very critical!!!

**Comment by CodeDoctorDE** [comment]
Can you reproduce it on https://butterfly.linwood.dev?

**Comment by ProgrammerLP** [comment]
no only in the preview version

**Comment by ProgrammerLP** [comment]
pls wait a minute

**Comment by ProgrammerLP** [comment]
full release works proberly

**Comment by CodeDoctorDE** [comment]
Can you try removing the cache and try again? I can't reproduce it

**Comment by ProgrammerLP** [comment]
ok

**Comment by ProgrammerLP** [comment]
https://user-images.githubusercontent.com/101939228/190455670-2e42109a-1c20-409b-b7a4-caf1b1aa19ea.mp4

**Comment by ProgrammerLP** [comment]
and test it in firefox

**Comment by ProgrammerLP** [comment]
bug is also in edge

**Comment by CodeDoctorDE** [comment]
I can replicate it now. It won't be deleted, it's under other objects

**Comment by CodeDoctorDE** [comment]
It should be fixed in the 2.0 version
