### ISSUE TITLE
[Bug]: Crashes after using trime in text label.

### ISSUE THREAD

**Issue by ghost** [LinwoodDev/Butterfly#313]
### What happened?

I use trime with [bambooin's rimerc](https://github.com/bambooin/rimerc) .
![IMG_20221117_172140](https://user-images.githubusercontent.com/118101099/202425809-f9235458-3e64-49db-a638-c6961a9ddc61.jpg) 
![IMG_20221117_172149](https://user-images.githubusercontent.com/118101099/202425850-64a9f7b6-23c2-4455-a05d-1a55fbb41fa2.jpg) 
![IMG_20221117_172047](https://user-images.githubusercontent.com/118101099/202425885-ffd99c93-7f80-487f-a352-4b05686af9d3.jpg) 
When inserting a text label, if I press "Shift" in trime and long-press a key, Linwood Butterfly crashes.

### Version

1.5.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, I need to look how I can reproduce it. To fix this I need an error log

**Comment by CodeDoctorDE** [comment]
Can you try the latest alpha (1.6.0-alpha.1) and give the error?
I added an error screen

**Comment by esh2022** [comment]
> Can you try the latest alpha (1.6.0-alpha.1) and give the error? I added an error screen

It didn't show a window.

**Comment by esh2022** [comment]
> Can you try the latest alpha (1.6.0-alpha.1) and give the error? I added an error screen

It didn't show a window.

**Comment by CodeDoctorDE** [comment]
I updated the flutter version. Does it appear again?

**Comment by CodeDoctorDE** [comment]
I would close this issue. If this bug happens again in the 2.0 version, feel free to reopen the issue.
