### ISSUE TITLE
[Bug]: Use Notch Area while in Full screen mode

### ISSUE THREAD

**Issue by xmha97** [LinwoodDev/Butterfly#368]
### What happened?

Use Notch Area while in Full screen mode:

Non full-screen mode:
![Screenshot_2023-04-15-15-16-55-083_dev linwood butterfly](https://user-images.githubusercontent.com/23485114/232216759-52e943fe-013d-40b6-a6ab-0fc7dd77721b.jpg)

Full-screen mode:
![Screenshot_2023-04-15-15-17-00-293_dev linwood butterfly](https://user-images.githubusercontent.com/23485114/232216774-3149fbc8-8a13-4e7b-86d8-6261bb60fd6a.jpg)

### Version

2.0.0.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
But then, it isn't really full screen anymore?

**Comment by xmha97** [comment]
No,
I think it's my issue:
https://github.com/flutter/flutter/issues/46486

**Comment by CodeDoctorDE** [comment]
Oh thanks.
I will try using `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item`.
But I don't think I can try it on an emulator and my phone hasn't a notch.
It would be nice if you will try the next alpha (2.0.0-alpha.2).

**Comment by CodeDoctorDE** [comment]
Hmm, I see `<item...>` was already there.
I will investigate it further

**Comment by xmha97** [comment]
> It would be nice if you will try the next alpha

Sure 👍

**Comment by CodeDoctorDE** [comment]
![image](https://user-images.githubusercontent.com/20452814/232400375-5ff2f4ee-bb0c-470f-a828-e4baaa4ab9af.png)
I can confirm this bug

**Comment by xmha97** [comment]
Also the background of the status bar is black on the light theme.

![Screenshot_2023-04-17-15-02-59-289_dev.linwood.butterfly.jpg](https://user-images.githubusercontent.com/23485114/232472790-f6512269-81e3-4bd7-8ea7-e1ff1247af20.jpg)

I think it should be white when dark mode is off.

**Comment by CodeDoctorDE** [comment]
Hmm, currently I couldn't find a way to fix it.
If anyone wants to help me, feel free to create a pull request.

**Comment by MrGumpIT** [comment]
Maybe I have found the problem
this is the current behaviour of the app


![Image](https://github.com/LinwoodDev/Butterfly/assets/47901429/599da17d-4ac0-4bcd-b226-9832501da572)

this probably  is what you would like to see.


![Image](https://github.com/LinwoodDev/Butterfly/assets/47901429/8ab13ad0-7174-4933-9df5-6f9b2b93cf64)

**Comment by CodeDoctorDE** [comment]
I think you found a fix. Feel free to make a pr for this, and I will try to release it with 2.0.3

**Comment by CodeDoctorDE** [comment]
I think you found a fix. Feel free to make a pr for this, and I will try to release it with 2.0.3

**Comment by CodeDoctorDE** [comment]
Thanks to @MrGumpIT, it will be released on Monday in 2.0.3-rc.0
