### ISSUE TITLE
[Bug]: Default installation path

### ISSUE THREAD

**Issue by xmha97** [LinwoodDev/Butterfly#371]
### What happened?

Butterfly is a 64-bit app.

![image](https://user-images.githubusercontent.com/23485114/233867776-eb1025f1-8fd0-4fe1-a863-374c97bdb445.png)

It should install on "C:\Program Files" not "C:\Program Files (x86)"

![image](https://user-images.githubusercontent.com/23485114/233867878-8bd6955a-3831-4b1b-8c80-987e62e5293f.png)

### Version

2.0.0-alpha.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixed in v2.0.0-alpha.2

**Comment by xmha97** [comment]
Thanks 🙏
