### ISSUE TITLE
[Feature request]: Hide start screen links

### ISSUE THREAD

**Issue by xmha97** [LinwoodDev/Butterfly#372]
### Describe your feature request!

Please add an option to customize the start screen.
I want to hide **"What's new?"** and **"Documentation"**

# ❌ Actual Behavior
![Untitled](https://user-images.githubusercontent.com/23485114/233874590-8516f219-387a-4584-adf7-4d5eff50d00b.png)

# ✔️ Expected Behavior
![Untitled](https://user-images.githubusercontent.com/23485114/233874600-189d62c7-c270-4bff-ac5d-8313e7fc802d.png)

Thanks 🙏

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Is it to big?
Should there be an option to show it after an update?

**Comment by CodeDoctorDE** [comment]
That's cool. Feel free to share your progress on the matrix or discord server.

There are links also in the settings and in the painter properties view.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-alpha.2.
