### ISSUE TITLE
[Bug]: GTK header bar shows up while starting the app

### ISSUE THREAD

**Issue by soumyaDghosh** [LinwoodDev/Butterfly#385]
### What happened?

When I start the app, it shows the gtk header bar first, then it shows the app's own header bar.

[Screencast from 2023-05-19 00-28-35.webm](https://github.com/LinwoodDev/Butterfly/assets/72045785/59b47236-a577-4543-88b3-d8774de6c1e0)

I think the custom widget, you're using, needs to be initialized first. I think there is something error in Future await async. Furthermore, I am not a flutter pro, so, sorry if I make some mistake analyzing the error.

### Version

2.0.0-alpha.3

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm yeah, I will look at it...
A solution would be to show the app only after it finished initializing

**Comment by soumyaDghosh** [comment]
> Hmm yeah, I will look at it... A solution would be to show the app only after it finished initializing

For any contributions, is the develop branch the main, or should I contribute in the main branch

**Comment by CodeDoctorDE** [comment]
The main branch is only for stable releases, develop is the branch for you!
https://pub.dev/packages/window_manager
This is the package I use for the custom title bar, we need to follow the `Hidden on launch guide` and run the show method after setting the title bar style in the `main.dart` file

**Comment by soumyaDghosh** [comment]
No, actually, I want to push updates for a package, as I have said before. Sorry about that, I am still just learning flutter.

**Comment by CodeDoctorDE** [comment]
What do you mean with "push updates"?

> Sorry about that, I am still just learning flutter

You can also learn by contributing :)

**Comment by soumyaDghosh** [comment]
> What do you mean with "push updates"?
> 
> > Sorry about that, I am still just learning flutter
> 
> You can always learn by contributing :)

I making the snap package, easy to maintain and more clean. That's what I meant. So, for not being clear about that.

**Comment by CodeDoctorDE** [comment]
Oh, there is already one: https://snapcraft.io/butterfly

**Comment by soumyaDghosh** [comment]
The comma should not be there, 
I'm making the snap package easy to maintain and more clean
Typo mistake
:sob:

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-alpha.4
