### ISSUE TITLE
[Feature request]: Add ability to customize position the toolbar

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#408]
### Is your feature request related to a problem? Please describe

I am a teacher, planning to use this notetaking & whiteboard app. I am planning to use it in a classroom on large 6x4 feet interactive panel running android. Reaching out to the toolbar items at the top is quite difficult.
 

### Describe your feature request!

Please add ability to customize the toolbar

in settings as done in [saber](https://github.com/adil192/saber) app

![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/d6ff88ad-a1c1-4e3f-a0b5-e33bac621af7)
 
or allow it to be draggable around the screen. So that it can be used by uses as per the need.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for your ideas!
That's a good idea, I will add it to my todo list

**Comment by CodeDoctorDE** [comment]
On mobile devices we can't do this.
I will add a note that this is only available on larger screens

**Comment by CodeDoctorDE** [comment]
![Image](https://github.com/LinwoodDev/Butterfly/assets/20452814/199eccf7-e8ba-497f-afd2-8787e616ed2c)



Added in 2.0.0-beta.3
