### ISSUE TITLE
[Feature request]: Add lasso select

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#409]
### Is your feature request related to a problem? Please describe

Currently there don't seem to be a separate selection tool.

Current workflow for selection seems to be (correct me if I'm wrong):
1. write with pen
2. switch to handmode
3. drag and do **rectangular selection**
4. open context menu (by rightclick/press and hold) 
5. select move or scale.

Rectangular selection is inconvenient for handwriting apps.

 

### Describe your feature request!

Implement:
- Lasso select (or polygon select) which is offered in onenote and other similar apps.

On a side note: [rnote](https://github.com/flxzt/rnote) offers the best selection tool with 4 modes of selection.
1. rectangular selection
2. Lasso select (or polygon select) 
3. Select intersecting path
4. Select one by one 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The hand tool should be the selection tool.
Then we can add more modes to it.
I would rename the issue to `Add lasso select`.

**Comment by CodeDoctorDE** [comment]
A few links how to implement this:
* https://en.wikipedia.org/wiki/Point_in_polygon
* https://jeffe.cs.illinois.edu/teaching/comptop/2009/notes/jordan-polygon-theorem.pdf

These are point in polygons problems but I think we can check if the center of the element is inside this polygon

**Comment by CodeDoctorDE** [comment]
I mark this as https://github.com/LinwoodDev/Butterfly/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 for people that wants to help the project and look where they want to start.

Here are a few rough steps of what to do:
1. Try to get the theoretical idea how to implement this
2. Add new polygon file and class in https://github.com/LinwoodDev/Butterfly/tree/develop/api/lib/src/models
3. Add new `hitPolygon` function for https://github.com/LinwoodDev/Butterfly/blob/develop/app/lib/renderers/renderer.dart#L45
4. Implement this for `DefaultHitCalculator` and `PathHitCalculator`
5. Add a new function `rayCastPolygon`in https://github.com/LinwoodDev/Butterfly/blob/develop/app/lib/handlers/handler.dart#L282 and run the `_executeRayCastPolygon` function with compute
6. Add a new function `_executeRayCastPolygon`. For reference how to do this, look at the `_executeRayCast` function. Here run this `hitPolygon` function
7. Add new enum `HandSelectionType` with values `rect` and `polygon` in https://github.com/LinwoodDev/Butterfly/blob/develop/api/lib/src/models/painter.dart
8. Add a new property `selectionType` in the Painter.hand constructor and set `polygon` to default.
9. Add `() => Painter.hand(selectionType: HandSelectionType.polygon` to https://github.com/LinwoodDev/Butterfly/blob/develop/app/lib/dialogs/add.dart#L190
10. Change name and icon for this special hand in https://github.com/LinwoodDev/Butterfly/blob/develop/app/lib/visualizer/painter.dart

You are done. Please contact me on matrix or discord if you have questions. After that you can create a pull request.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.8
