### ISSUE TITLE
[Feature request]: Improve UX of moving, scaling & rotating

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#410]
### Is your feature request related to a problem? Please describe

Firstly, I couldn't find ability to rotate the selection. (#412 )
Secondly, the current workflow for selection seems to be (correct me if I'm wrong):
1. write with pen
2. switch to handmode
3. drag and do **rectangular selection**
4. open context menu (by rightclick/press and hold) 
5. select from the context menu actions like move or scale.

these are too many steps.

### Describe your feature request!

I think having a selection tool (#409 ) 

and then upon select (by default):
1. show scaling & rotation icons on the box
like this: 
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/0b770af0-b889-479a-846b-ad61c7d04764)
 
2. dragging on selection should move selection
3. more icons could be shown by default  (like duplicate, arrange, delete) in the form of icons

This avoids press & hold to open context menu. For serious notetakers and users who are using to plan something it saves lot of effor.

What would be ideal is if what is shown by default is customizable somewhere. So that users can choose what actions on selection they need based on their usecase.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Moving by dragging the selection and showing the scaling options by default is a good idea!

> more icons could be shown by default (like duplicate, arrange, delete) in the form of icons

What do you mean with that? These are currently in a context menu. Where do you want to move these actions?

**Comment by claws99** [comment]
> > more icons could be shown by default (like duplicate, arrange, delete) in the form of icons
> 
> What do you mean with that? This is currently a context menu. Where do you want to move these actions?

What I mean is if user is selecting object(s) (like strokes or images), its safe the presume that he'd want to do one of these actions. So 
1. lets eliminate "press&hold or righclick" step to open context menu
2. Lets substitute context menu with just icons (one for each of these actions) and have it positioned around the selection dotted box. something like this: 
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/7f5c4590-d3e8-4f66-b841-85c4103676b6)
(these icons aren't ideal nor does that black background. Could be better designed. It communicates my point.

try: doing doing hold and drag on the canvas [here ](https://wireframe.cc)(no need to select anything) 

Why do we want to do that, you may ask? Because context menu isn't an ideal UI for two reasons:
1. as you said in another issue, lets not occupy much space on the screen. Context menu occupies good amount of space.
2. For choosing an action, icon serves as an easier visual recognition element than "text" (read all the items of the menu vs pick the standard established icon for that action)

**Comment by CodeDoctorDE** [comment]
This can look good on mobile devices but as a desktop user, I'm more familiar with context menus.
Maybe we can find a midddle way for both of these?

**Comment by CodeDoctorDE** [comment]
1. + 2. is now implemented in 2.0.0-beta.4

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.8
