### ISSUE TITLE
[Feature request]: Improve UX of adding a new page - single click add new page

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#411]
### Is your feature request related to a problem? Please describe

What I love about this app is that pages are not of fixed size. So while writing, running out of space is off the mind. Yet ability to organize notes into pages is good for the longterm.

But adding new page shouldn't come in the way of writing.

Rightnow the while writing if I want a new page, the workflow seems to be: (correct me if I'm wrong)
1. click butterfly icon on the top left
2. select `navigator`
3. choose pages tab
4. click `+ create` button at the bottom
5. Think of a name for the page
6. type the page name
7. hit create
8. then resume writing

These are too many steps. Other apps (even OneNote) offer single click add new page.

### Describe your feature request!

**Solution:**

- single click `add new page button` at the bottom (or to the customizable toolbar: #408 ). 
and start writing. 

some default page name can be created like Page1, Page2, which could be edited later.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yeah, the workflow seems a bit too long.
These are currently beta releases, so not every feature is finished.
Currently you can't rename the pages but I'm currently working on it.
Adding the pages with a single click and renaming it later is a good idea.
But I'm looking for a nice way where we can add the dropdown without wasting too much space on small devices.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.3
