### ISSUE TITLE
[Feature request]: Implement Rotation of selection

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#412]
### Describe your feature request!

I don't see rotation of selection to be present. (Correct me if I'm wrong)

after  shapes, images, strokes rotating them becomes an essential thing.

related to #410 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for your ideas!
Added to my todo list

**Comment by CodeDoctorDE** [comment]
Todos:

- [ ] Rotate the hit calculation of these rects
- [ ] Rotate the selection rect (or expand it)
- [ ] Use the expanded rect in 2 and test with this if the element is inside the viewport and only then render it

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.3
