### ISSUE TITLE
[Feature request]: add a real full screen mode (No distraction mode)

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#421]
### Is your feature request related to a problem? Please describe

in the fullscreen mode, currently the logo, search box and the entire top bar is visible. 

### Describe your feature request!

hide the top bar in fullscreen mode. So that use can work with just the toolbar & pen colors UI  and large canvas area. Making it truly a no distraction mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.3
