### ISSUE TITLE
[Bug]: Insert image within the current view

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#423]
### What happened?

when an image is inserted. Its inserted out of my viewport. 
I think it should appear in the center of thescreen/viewport?

### Version

Insert image within the current view

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.3 in https://github.com/LinwoodDev/Butterfly/commit/f71ac63bbd1e3b4a28a5fa6fe7630aed5eaca420
