### ISSUE TITLE
[Feature request]: Implement Insert Vertical Space tool

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#424]
### Is your feature request related to a problem? Please describe

once you have a pageful of handwritten notes. You want to insert something in between. 
The current way (which is inefficent) is to:
1. select all the objects below insertion point
2. move  down
3. then write

### Describe your feature request!

Implement OneNote's `Insert Vertical Space`

![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/efb21bed-7af3-44b4-8900-483410eb15fb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Im currently thinking: maybe we can extend it by a horizontal spacer. If we implement a vertical one, a horizontal ones won't be complicated

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.4
