### ISSUE TITLE
[Bug]: Add custom mouse cursors for painters

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#426]
### What happened?

When pen tool is selected (especially on desktop devices & touch devices with mouse plugged in). Change the mousepointer to pen icon.

Currently even if I select pen tool or hand tool. the mouse pointer is the same. Its confusing and its bad UI&UX practice. All other apps do it right. Example checkout: https://tableaunoir.github.io

### Version

2.0.beta2

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I would not classify this as bug but we could add it.
I don't see a real pen cursor in the system mouse cursors. Here is a list what is available: https://api.flutter.dev/flutter/services/SystemMouseCursors-class.html

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.4
