### ISSUE TITLE
[Bug]: Window does not open with start in fullscreen mode enabled

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#430]
### What happened?

When you open it in Windows 11 (with `start in fullscreen mode` option enabled). It is probably stuck in some infinite loop trying to go full screen.

Its been the case with atleast last 4-5 commits. I don't see any problem on android. Didn't try in Linux.

### Version

beta-3 release

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I can reproduce it. I will fix that as soon as possible.
It is also reproducable in the latest nightly and on the develop branch

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.4
