### ISSUE TITLE
[Feature request]: Make Import options addable to toolbar

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#431]
### Is your feature request related to a problem? Please describe

Currently these can't be added to the edit toolbar.

Import options:
- Image
- Camera
- SVG
- PDF
- Document

depending on the user any of these can be port of their regular notetaking workflow.

In my case, adding images is as comman as changing pen color. Almost every page & note includes multipe images.

### Describe your feature request!

Give these the same ability painters have. To be able to add to toolbar.
Import options:
- Image
- Camera
- SVG
- PDF
- Document

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
There is an internal import handler that we can use for this.
We can add a pin icon in the top right corner of these items in the add dialog to add this new “import” painter.

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.5
