### ISSUE TITLE
[Feature request]: Move Fullscreen to Actions so that it can be added to the toolbar 

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#432]
### Is your feature request related to a problem? Please describe

Having a same workflow for entering and exiting fullscreen seems a better and consistent UX practice.

Currently, exiting toolbar is done via toolbar with single tap/click on toolbar. But if you want to renter fullscreen, the first thought is to look at the same spot.

But it has to be done from menu> full screen.

### Describe your feature request!

Solution I propose is:

- add/move fullscreen to Actions (you can leave it in the menu if you like)
- user can add this action to the toolbar.
- From toolbar > enter and from toobar exit
- icon of the toolbar changes depending on the state of fullscreen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.4
