### ISSUE TITLE
[Bug]: resizing & rotation is buggy

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#434]
### What happened?

resizing is buggy

https://github.com/LinwoodDev/Butterfly/assets/83898279/d9178fa6-9565-4877-b616-e9c6ea962cd4

This is how it should work:

https://github.com/LinwoodDev/Butterfly/assets/83898279/7efe0cf6-ebf1-45c1-922a-3ef564ce427b

Same is the case with Rotation.

### Version

2.beta-3

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claws99** [comment]
For mysake, can you please tell me why this is happening?

**Comment by CodeDoctorDE** [comment]
I would think it happens because the pivot elements from where you scale is not correct when scaling multiple elements

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.4
