### ISSUE TITLE
[Feature request]: Keyboad shortcut `ctrl+a` - select all objects in the current page

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#436]
`ctrl+a` - select all objects in the current page

**Comment by CodeDoctorDE** [comment]
I don't like permanent issues, I would finish adding these shortcuts and would close it and if anyone needs another shortcut we could add it with a new issue

**Comment by claws99** [comment]
makes sense. 👍

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.5
