### ISSUE TITLE
[Bug]: Duplicate isn't working

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#437]
### What happened?

duplicate selection isn't working

### Version

2.beta-3

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This was because of my recode of the hand painter. The latest nightly release shouldn't have the problem.
I forgot to readd duplication of the selection.

**Comment by CodeDoctorDE** [comment]
Fixed in https://github.com/LinwoodDev/Butterfly/commit/76dd0363a39dea64562e352abfd071c1a51f3b56
