### ISSUE TITLE
[Feature request]: Improving Mobile UX - Make Navigator in the menu a submenu

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#442]
### Is your feature request related to a problem? Please describe

Right now `Navigator` is an item in the menu. The point of navigator is it takes us to other things. Then let's make it a submenu

### Describe your feature request!

Navigator > 
- Waypoints
- Layers
- Pages
- Files

So that directly user can go the navigator item he desires.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Modified to:
instead of a submenu we add this to the real menu and use a divider to separate this section

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.5
