### ISSUE TITLE
[Feature request]: Improving UX - Easier page browsing - Flipping through pages

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#443]
### Is your feature request related to a problem? Please describe

Currently the two ways of going to the next page or previous page are:

**Method 1**
1. click add page in toolbar
2. identify the previous/next page from the list
3. click  desired page

**Method 2**
1. click Menu 
2. identify Navigator from menu items
3. cchoose `Pages` tab
4. identify the previous/next page
5 click desired page

None of these are ideal

### Describe your feature request!

Add `Previous`, `Next` buttons and `Pagenumber` UI
something like this:
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/c6af251f-de5b-4cf2-9ad4-82a33a0f16b1)
 
Its implemented other notetaking apps, as it makes flipping through pages very simple.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claws99** [comment]
This could be a separate UI element (not on the edit toolbar) capable of positioning separately on the screen.

**Comment by CodeDoctorDE** [comment]
Hmm, how should it be aligned with the zoom view?
Maybe blocked by #425 ?

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.6
