### ISSUE TITLE
[Feature request]: Improving UX: Implement sleek sidepanels for single click navigator items access

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#444]
### Is your feature request related to a problem? Please describe

Rightnow if I have to go to layers, or pages or for that matter any navigator item. The method is quite cumbersome.

### Describe your feature request!

**Solution:** Single Click access to navigator menu item (Layers, Pages etc..)

Implement sleek sidepanels something like this:

Example from vscode:
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/8cacd580-07b9-432f-a1dd-083ca0a53269)

Example from a pdf reader:
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/4d463828-d6d6-4b5d-a623-18a80670b31c)

Example from vivaldi browser (similar UI is seen in Edge browser too)
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/8a151231-cdf2-4b65-8f91-7a7fc5ff4d5f)

### Additional context

We can then get rid of horizontal tabs in navigator panel
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/dc3b0ff1-78d0-43f9-bdc6-5326e37cda8b)

Once the single click access to `Pages` panel is available, it gives a proper UI to implement, (page reorganizing, page reordering, inserting pages in between (#425 )

We can also get rid of this menu:
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/eb1813d7-3fdf-481b-a43d-652280ab37f9)
Then add new page will be reduced to a single button and truly be a `single click add new page`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Maybe related to #442 ?
How do we do this on mobile devices where you don't have enough horizontal space to add this?

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.5

**Comment by claws99** [comment]
> How do we do this on mobile devices where you don't have enough horizontal space to add this?

For reordering pages, accessing layers  and other things, we anyways need the side panel even on small screen. 

How about something like this:

https://github.com/LinwoodDev/Butterfly/assets/83898279/d74c700f-e7e8-4194-bb50-fd45eeed8fd3


Infact, this could be given as an option on all screens (like Google Maps does). It gels well with the minimalistic UI interface.

**Comment by claws99** [comment]
related: #442

**Comment by CodeDoctorDE** [comment]
Hmm we can hide everything in the toolbar at the left of the book icon
