### ISSUE TITLE
[Feature request]: Get rid of the white bar behind the toolbar

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#445]
### Is your feature request related to a problem? Please describe

I don't find any utility of the white bar behind the toolbar (if positioned in left, right and bottom positions). 
Its unnecessarily occupying the screen space and visually distracting.
IMO its safe to get rid of it.

### Describe your feature request!

Get rid of the white bar behind the toolbar.

If deleting it isn't possible, then we can set its Opacity = 0%

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
It's the windows vs mac style.
On windows you have a whole space filled with the color vs mac where you have a dock that floats only on the center.
If it's better I will try implementing the floating style in butterfly. If the dock needs more space it will get larger

**Comment by claws99** [comment]
>If it's better I will try implementing the floating style in butterfly. If the dock needs more space it will get larger

I think that's a great idea.

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.4
