### ISSUE TITLE
[Feature request]: Transparent background

### ISSUE THREAD

**Issue by xmha97** [LinwoodDev/Butterfly#448]
### Is your feature request related to a problem? Please describe

Hi, please follow the system theme for the background color. (like the Xmind app or Microsoft Word)

https://github.com/LinwoodDev/Butterfly/assets/23485114/52fb3be4-5ed9-4735-a09d-6ebeb9038259

### Describe your feature request!

This feature helps to work with the app more easily day and night.

![image](https://github.com/LinwoodDev/Butterfly/assets/23485114/c3ab793c-aaee-4373-a0e2-8a7b8176fe9b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Personally I don't like this feature.
On OneNote when editing pdfs it does not make sense if my black pen strokes changes to white on a white pdf document.
Do you have an idea how we can prevent this?

**Comment by CodeDoctorDE** [comment]
And another aspect:
I want that everything looks the same on all devices. That would be problematic here

**Comment by xmha97** [comment]
> Personally I don't like this feature. On OneNote when editing pdfs it does not make sense if my black pen strokes changes to white on a white pdf document. Do you have an idea how we can prevent this?

I have no idea, I just know that the white background is annoying at night.
In the worst case, the whole board becomes negative.

**Comment by xmha97** [comment]
> And another aspect: I want that everything looks the same on all devices. That would be problematic here

Only use OS theme as background, if at first used transparent template.

**Comment by CodeDoctorDE** [comment]
> > And another aspect: I want that everything looks the same on all devices. That would be problematic here
> 
> Only use OS theme as background, if at first used transparent template.

You mean, on creation? That it sets the background when creation and keeps it like a solid background?

**Comment by CodeDoctorDE** [comment]
> You mean, on creation? That it sets the background when creation and keeps it like a solid background?

I don't see a difference by clicking on dark or light template or clicking on transparent with this approach.

When the background changes on system theme change then the document doesn't look the same on every device. This was important for me for this app.

**Comment by xmha97** [comment]
> When the background changes on the system theme change then the document doesn't look the same on every device. This was important for me for this app.

I don't want to break this project or make users unhappy, if you think this feature is not suitable for your project, please close this issue.

**Comment by CodeDoctorDE** [comment]
Yes, I think this change would break the consistency of this app.
Thank you anyway for your idea
