### ISSUE TITLE
[Feature request]: `Ctrl+A`  should select all objects irrespective of current selected painter/tool

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#450]
### Is your feature request related to a problem? Please describe

Currently `Ctrl+A` selects all objects in the current page (#436 ).

But it does that only when Hand Tool is selected. It should do this even when pen tool is selected. 

### Describe your feature request!

This is how it should behave:

user in pen mode:
- hits `ctrl+a`  using keyboard
- selects all objects on page
- tool mode automatically switch to select

Why?

**Principle:**
Pen, Mouse and Keyboard are different input tools and should be treated independent of each other. Hand tool is a way to select objects using pen or Mouse. Whereas, `Ctrl+A` is a way to select objects using keyboard.  It shouldn't depend on whether hand tool is selected by mouse.

**Better UX:**

When user is drawing with pen or mouse using pen tool, User hits `ctrl+a` to select all objects and does some actions on the selected objects and resumes writing. Without needing to manually switching to hand tool.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The selection system is implemented in the hand tool.
What we can do is adding a temporary hand tool when you use the shortcut.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.7
