### ISSUE TITLE
[Feature request]: Convert Add page button in toolbar to truly one click add page button & change icon

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#451]
### Is your feature request related to a problem? Please describe

Add Page button isn't a single click/tap add page 

 With implementation of sleek panel #444 , There is no utility  of showing pages in add page button. 
 
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/940ffd52-0b20-4ac6-8a28-430015097b60)

Also, its not really single click. Its 2 clicks now

### Describe your feature request!

- [ ] Get rid of the menu for add page button
- [ ] single click should add page
- [ ] Change icon of [add page button](https://www.flaticon.com/search?word=add%20page)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
But yeah, it's not really a single click

**Comment by claws99** [comment]
Consider changing the icon of add page from book icon to something with a plus button. See [this](https://www.flaticon.com/search?word=add%20page)

**Comment by CodeDoctorDE** [comment]
Partially blocked by https://github.com/phosphor-icons/homepage/issues/341

**Comment by CodeDoctorDE** [comment]
The current button was replaced with the lock button. I think if we add a "Add page" button to this menu it will get very big

**Comment by CodeDoctorDE** [comment]
Because of inactivity, I will close this issue. Feel free to create a new one if you need something or join the discord/matrix server.
