### ISSUE TITLE
[Feature request]: Improving UX - double click to rename pages & change the UI for renaming

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#452]
### Is your feature request related to a problem? Please describe

enhance the renaming pages.

### Describe your feature request!

- [ ] shortcut: double click/double tap on page name should  show rename UI
- [ ] Renaming UI:  Instead of a dialog, renaming there itself. (it will be consistent with the rename in files)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.7
