### ISSUE TITLE
Enhancement - insert image to fit the current view

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#454]
### Is your feature request related to a problem? Please describe

currently insert image, inserts the image in full size. Its a problem because we often download images and they can be pretty large. Resizing after inserting is also quite problematic (try inserting some random large image)

![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/b8d5807d-ff3b-4311-bf3d-a1df2b6c2c2f)

### Describe your feature request!

Solution:

insert the full size image if it fits  in the current viewport.  If not scale it down to current viewport and give an option to the user if he intends to insert the fullsize image.

All notetaking softwares (including OneNote) do these.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
We can also allow resizing if it is less than 30%. Then we can also fit the best.

Then we can also allow fitting with the zoomed view

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.7
