### ISSUE TITLE
[Feature request]: Improving UX - Implement Toggle Zoom Lock button

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#455]
### Is your feature request related to a problem? Please describe

while in pen mode, if the user uses atleast his 2 fingers and drags, the canvas should scroll in the direction of drag. But it should atleast scroll up and down.

But 2 finger drag might clash with pinch and zoom touch-event. 

So all other apps implement zoom lock button/mode. When this button is active (zoom is locked to current zoom level) and dragging with any number of touch fingers will only scroll and not zoom.

### Describe your feature request!

Implement Toggle Zoom Lock button which will lock zooming

If this mode/button is not active, it will both scroll and zoom.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
> Implement Toggle Zoom Lock button which will lock zooming

Where do you want this button? I don't want to add too many things on the toolbar

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/8e089a1f-8064-44cd-b179-e10c11f141c2)
I'm currently working on it.
There was a user on the discord that wants to disable horizontal moving so I added a popup menu to the lock feature.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.7 (1fbe1b575f9dc23c5d7be6f1f521bec1e8410a4a)
