### ISSUE TITLE
[Feature request]: Create a button to toggle panel on all screens

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#458]
### Describe your feature request!

Create a button to toggle panel on all screens, 
- for minimal UI
- for smaller screens

https://github.com/LinwoodDev/Butterfly/assets/83898279/d74c700f-e7e8-4194-bb50-fd45eeed8fd3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Currently this navigation rail is only available on screen width > 700.
I don't think an opener for a large 100 wide navigation rail is good on smaller uis.
I would prefer leaving it in the menu. What do you think?

**Comment by CodeDoctorDE** [comment]
There is a full screen mode now, I would remove this issue from the roadmap for now and put this issue on discussion.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.8
