### ISSUE TITLE
[Bug]: Scroll not happening on Samsung tab S7

### ISSUE THREAD

**Issue by mounicakasturi** [LinwoodDev/Butterfly#460]
### What happened?

A bug happened ! I installed the latest version of the app on Samsung Tab S7 FE and I am unable to scroll the page. I am only able to zoom in and zoom out.

 

### Version

v2.0.0-beta.5

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi
I tested it on my device and it works fine.
You can move by dragging the screen with two fingers.
Which painter did you select?

**Comment by claws99** [comment]
I confirm this. Irrespective of which painter it's selected, scroll isn't working.

**Comment by CodeDoctorDE** [comment]
Okay, feel free to reopen this issue if it appears after the next 2.0.0-beta.6 update
