### ISSUE TITLE
[Feature request]: Implement Real time Erasers

### ISSUE THREAD

**Issue by mounicakasturi** [LinwoodDev/Butterfly#461]
### Is your feature request related to a problem? Please describe

I am using the eraser tool for my free hand drawings.  Once I select the eraser tool, the changes are not made real time. I have to first finish using all the eraser strokes that  I want, then wait for the changes to be reflected and then again use the eraser to get the desired result. 

### Describe your feature request!

Real time eraser be implemented please. So that its easy to use and changes and corrections can  be implemented without having to wait. Its a otherwise very hard to use for sketching. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
On the todo list, also related to #438

**Comment by CodeDoctorDE** [comment]
For this to work we need to disable renderers for a specific part of the view. Related to #438
I will implement this after the 2.0 update

**Comment by CodeDoctorDE** [comment]
I have an idea how to implement this. I add it to my todo list

**Comment by CodeDoctorDE** [comment]
The eraser updates on every move it didn't work with my current solution. I will remove this issue from my current todo list

**Comment by MrGumpIT** [comment]
I too have experienced strange behavior from the eraser on both Windows and Android, it often leaves points, even difficult to erase.

https://github.com/LinwoodDev/Butterfly/assets/47901429/24c5df66-9a7c-461b-a59d-e58deb3369e8

i try to modify code

https://github.com/LinwoodDev/Butterfly/assets/47901429/1034720f-de0e-49d4-8690-2a6a0165244a

I tried to determine a different way to erase the points, for getting an more precise eraser

**Comment by MrGumpIT** [comment]
This project is teaching me a lot and I really like it. Thank you.I’m still doing some tests and then I’ll make a PR

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.3-rc.0
