### ISSUE TITLE
[Documentation]: Create a new "Enhancement" template for reporting issues

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#462]
### Describe your feature request!

Please create a new section called "enhancement" for reporting issues.
![image](https://github.com/LinwoodDev/Butterfly/assets/83898279/6e518f9c-b80e-49e5-a8c1-4d671dcd7d01)

These are for tweaking of things rather than a full fledged feature implementation.

Suggestion:
`enhancement ` label can be reserved for these enhancements and a new lable `feature-request` can be  used for feature requests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm,
I see your point. But how can we difference these?
Is a new file format a new enhancement?

**Comment by claws99** [comment]
These aren't clearly black & white. The lines can get blurred on issues. But for things like adding  or changing keyboard shortcuts, UI tweaks etc can be classified as enhancements.

We can use combination of parameters like:
- amount of work it takes
- the feature in question is already offered by the app and needs a slight modification 
- few predetermined categories 
can come be used to broadly distinguish.

If needed we may call it `minor-enhancement` and `feature-request` to make the distinction even wider.

**Comment by CodeDoctorDE** [comment]
Okay, added https://github.com/LinwoodDev/Butterfly/labels/feature-request.
Now I need to look what to change for the template between enhancements and feature requests https://github.com/LinwoodDev/Butterfly/blob/develop/.github/ISSUE_TEMPLATE/feature_request.yml

**Comment by CodeDoctorDE** [comment]
Added issue template for feature requests and enhancements.
Feel free to answer on existing issues to fix the label
