### ISSUE TITLE
[UI Enhancement]: Change all slider UIs to Input Stepper 

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#463]
### Is your feature request related to a problem? Please describe

currently to change any number in settings (eg: thickness or width of stroke etc.) the UI element used is a slider.

Slider is not a better UI element because:
1. its imprecise, since we are adjusting by freehand.
2. it occupies too much space on screen 
3. to make it precise we have to make them longer, which occupies even more space

 

### Describe your feature request!

Replace them by Input Stepper 

![](https://media.nngroup.com/media/editor/2018/09/18/7_gpa.png)

![](https://media.nngroup.com/media/editor/2018/09/18/1_steppers.png)

It solves all the problems.

On each click, it can increment or decrement by 0.5. 
If one wants even finer control, they can input the number 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Do you want to replace all sliders?
I find sliders very useful to quickly change the stroke width of pens.
On these steppers, you need to click multiple times to get your desired width.

**Comment by claws99** [comment]
>I find sliders very useful to quickly change the stroke width of pens.

They are definitely quicker than steppers. But its hard to set the same value again. Its really hard without keyboard. 

Also it leads to inconsistency in stroke widths. Some stroke 2.04 another 2.02 or 1.92 etc. They might all look similar but its a bad practice. This UI is making it easier to do bad practice.

Also lot of the problems of modal sizes  #464  will automatically change with this UI gone.

**Comment by claws99** [comment]
On another note, I think the reason for existence of preference to hide Zoom UI is because of it being too big and its big because of slider UI.  The slider UI for zoom can be implemented in much better manner, but that's another issue. For  now hiding works.

**Comment by CodeDoctorDE** [comment]
Okay, i think about it and I think it's the best replacing the sliders with input stepper. I will put it on the todo list

**Comment by CodeDoctorDE** [comment]
![grafik](https://github.com/LinwoodDev/Butterfly/assets/20452814/d66e96b2-a7a6-4aba-95d2-51c6e383633c)
Do you like the first one better? Please react with :+1: or with :-1:

**Comment by CodeDoctorDE** [comment]
Because of inactivity, I will close this issue. Feel free to create a new one if you need something or join the discord/matrix server.
