### ISSUE TITLE
[UI Enhancement]: Reduce size of modals (everywhere in the app)

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#464]
### Is your feature request related to a problem? Please describe

This is how it looks on my tab:

Other Options are hidden, I've to scroll down to discover hidden options
![](https://dl3.pushbulletusercontent.com/5YDw0kMKKC1eXtLMYDj9mgpgn2aHTMie/1690458169499.jpg)

Its poor UI and Its makes the app look quite clunky.

### Describe your feature request!

Reduce size of modals so that everything is visible on screen. 

Users are used to working with clean and smaller UI elements on screen. We aren't adding any further value by making our App ui quite large.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
What do you want to change?
Do you want to reduce the size of the spacing at the edges of the dialog?

**Comment by CodeDoctorDE** [comment]
This is part of the dialog specs: https://m3.material.io/components/dialogs/specs#6771d107-624e-47cc-b6d8-2b7b620ba2f1.
If we make the space "smaller" it doesn't look material like anymore

**Comment by CodeDoctorDE** [comment]
Because of inactivity, I will close this issue. Feel free to create a new one if you need something or join the discord/matrix server.
