### ISSUE TITLE
[Bug]: Pasting an image not working

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#465]
### What happened?

#422 was closed as system clipboard was implemented. I'm testing it for the first time now. Its not working.

On windows 11, I snipped a part of screen and tried pasting in the app. It isn't pasting.

### Version

beta6

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, yeah. The image and svg elements stores only the path inside the element.
I will fix that so the clipboard data also hold the real data.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6

**Comment by CodeDoctorDE** [comment]
closed the wrong issue

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6

**Comment by claws99** [comment]
Its still not working for me (on windows)
