### ISSUE TITLE
[UI Enhancement]: Show stroke width on the pen icon in toolbar

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#466]
### Describe your feature request!

I create multiple pens with different stroke widths and always have multiple pen icons added to the toolbar. I have no way of knowing which pen icon corresponds to with stroke width. In other note taking apps this problem is solved by displaying the stroke width number on the pen icon itself. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claws99** [comment]
using names wouldn't be a substitute to this because hover feature is available on for pens which support hovering and mouse devices. That excludes lot of touch devices.

Yeah, even I am with you in keeping the design simple. It can be done without making it too big. It shouldn't be of the same font size. 

Another alternative (which isn't a good solution IMO) which other apps implement is:
Add predetermined strokewidths to colors toolbar. So that with single pen user can change both color and stroke width.

But I consider, the current solution implemented in our app is a better one. Its just that we need to find a way to provide visual distinction.

**Comment by CodeDoctorDE** [comment]
What about adding a new slider to the color toolbar to set the stroke width without opening the property view?
Then you can easily see what you select

Or maybe another widget to set the width.

**Comment by CodeDoctorDE** [comment]
Hmm, I would close this in favor of #467.
There is no space to add a text on the icon

**Comment by CodeDoctorDE** [comment]
Feel free to reopen it if you have a better ux
