### ISSUE TITLE
[Feature Request]: allow users to choose icon for pen in painter options

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#467]
### Is your feature request related to a problem? Please describe

There are various kinds of pens that users use such as ink pen, highlighter, brush pen, ball pointed pen etc. For each of these pen types, the stroke width, thinning and alpha are different. Now the problem is there is no visual way of identifying which pen is what.

Possible Solutions:

1. Making icons part of the style pack
2.  Have built in icon type and allow the users to choose the icon in pen painter options

### Describe your feature request!

Please implement one of the above solutions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I would keep the style and use only phosphor icons: https://phosphoricons.com/
but we can add a property in the pen painter which of these should be displayed: `pen`, `pencil`, `pencil-simple` or `pen-nib`

**Comment by claws99** [comment]
> I would keep the style and use only phosphor icons: https://phosphoricons.com/

 Style of icons is totally call. phosphor icons looks good. You may consider adding `highlighter-circle` also to the list

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.7
