### ISSUE TITLE
[Bug]: Unpredictable and undesirable behaviour of pasting the copied strokes/objects

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#468]
### What happened?

when pen strokes are cut/copied and the user opens context-menu for paste (by double-tapping or double-clicking) and hits paste. Its pasting but the location of paste is quite unpredictable, and I've to search for where it pasted.

I tested this on all platforms

**Solution:**
1. Open the context-menu for paste at the location where the user double clicked/tapped
2. When user hits paste, position the top-left corner of the content to be pasted at this location.

### Version

beta-6

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
When clicking on paste, you can move the clipboard content around by dragging your finger on the screen.
I will disable this feature when clicking on the paste button in the context menu and instead paste it on this position. I think that's the best behavior.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6 in https://github.com/LinwoodDev/Butterfly/commit/04c93118d655d590fe22ee6ee7685bea57d00059

**Comment by claws99** [comment]
- [ ] Open the context-menu for paste at the location where the user double clicked/tapped

This is behaving unpredictably. Sometimes its opening at the location of double click at other times its showing else where.

**Comment by CodeDoctorDE** [comment]
Oh yeah, I will fix that

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6
