### ISSUE TITLE
[Enhancement]: In home screen, enhance sort related functionality

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#469]
### Is your feature request related to a problem? Please describe

On Home/welcome screen of the app

1. Currently it doesn't remember the last sort order preference (by name, by modified etc.) 
2. Currently there is no way of allowing user to sort by Ascending. Default seems to be descending

### Describe your feature request!

Implement

- [ ] remember sort order preference

- [ ] implement, ascending, descending toggle button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea. I will put it on my todo list

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.6
