### ISSUE TITLE
[Bug]: Unable to export large drawing to PDF

### ISSUE THREAD

**Issue by mounicakasturi** [LinwoodDev/Butterfly#470]
### What happened?

I made a drawing of around 7 MB and wanted to export it into PDF. However the same is not being generated. Please check.

https://1drv.ms/u/s!Atm5H_ep57wDgZoecW3Cic1XXo1NNA?e=4b0gvR

### Version

v2.0.0-beta.5

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
You need to have areas to create pdfs and then you can add it to your pdf export

**Comment by CodeDoctorDE** [comment]
I will close this issue for now.
If you have questions, feel free to join the matrix or discord server or use the discussion functionality on this repository.
