### ISSUE TITLE
[Bug]: Unable to resize selected drawing

### ISSUE THREAD

**Issue by mounicakasturi** [LinwoodDev/Butterfly#471]
### What happened?

I am unable to resize the selected drawing as need. Attaching the video showing the issue. 

https://1drv.ms/v/s!Atm5H_ep57wDgZof0hQ1FIwDlAHlQA?e=WlCmsD

### Version

v2.0.0-beta.5

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Oh yeah, the detection is not very good when zoomed in. I fixed it already in https://github.com/LinwoodDev/Butterfly/commit/a77f82b99aaa013e22bee25bb70e77b4744a6702 and it should be land in 2.0.0-beta.6
