### ISSUE TITLE
[Bug]: Group rotation not working

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#472]
### What happened?

#434 is closed. But rotation is still buggy.

 

https://github.com/LinwoodDev/Butterfly/assets/83898279/a908a212-e77d-4970-b702-b1458e6c11bc

### Version

beta-5

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
On my todo list.
But currently it also looks cool

**Comment by claws99** [comment]
> On my todo list. But currently it also looks cool

hahaha!! definitely looks pretty cool.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6
