### ISSUE TITLE
[Enhancement]: Add move painter

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#473]
### What happened?

Its both a bug and a feature request.

On non-touch devices we use mouse scroll wheel to up and down. I want to scroll to the left and right, 

Or bring certain part of the canvas to the center of the screen. Or move the canvas to show desire part. There is no way to do that on windows. Ctrl+Zoomwheel is not a substitute for it. There has to be a better way

**Problem is arising because:**
Hand tool is selecting stuff on screen, which technically is the function of selection tool (in all other notetaking apps that's what it is called). Moving the canvas should be the job of hand tool. 

**Solution:**

- [ ] Rename the current Hand tool to selection tool & change its icon. (this later on allows us to add other selection modes to it  related #409)
- [ ] Implement hand tool like this:

https://github.com/LinwoodDev/Butterfly/assets/83898279/4e6e7227-202e-4d78-b0c8-bc2b994acc7e

 

### Version

beta5

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
On non touch devices you can use the shift key to move to the left or right, and the middle mouse button to move freely

**Comment by claws99** [comment]
icons `hand` and `hand-grabbing` on  for hand tool https://phosphoricons.com/

**Comment by claws99** [comment]
> On non touch devices you can use the shift key + scroll to move to the left or right, and the middle/right mouse button to move freely

aah! in that case, it will only become an enhancement then.

**Comment by claws99** [comment]
Can we please stick to the general terminology used by other apps ?

Hand tool and selection tool. (even pdf readers use same terminology)

Why break the accepted conventions and confuse the first-time users?

**Comment by CodeDoctorDE** [comment]
Tools are already taken for ruler and grid. But we can discuss this on the discord. That's just a new type that will be added

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.6

**Comment by CodeDoctorDE** [comment]
I would rename the hand painter after we discuss how we are naming things like painters

**Comment by claws99** [comment]
UI Enhancement: 
Change cursor state  to  `hand` on selection of tool
onMouseDown cursor start to `hand-grabbing`

**Comment by claws99** [comment]
Renaming & chaging icons:

The current hand tool needs to be
- renamed to `Select`
- icon changed to `selection`
