### ISSUE TITLE
[Enhancement]: Keep the selection ON after moving or rotating

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#478]
### Is your feature request related to a problem? Please describe

after selecting strokes and doing an operation on them (like moving or rotating) the selection (rectangular box) disappears. But the current tool is still selection tool. This disappearance offers no additional advantage.

### Describe your feature request!

Unless the 
- current tool is changed or
- a new selection is made or
- user taps/clicks outside selection

the selection should remain ON. This allows the user to perform:
1. other operations on the selection
2. fix/correct his earlier operation (like moving slightly more or fixing rotating a bit etc)  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-beta.6
