### ISSUE TITLE
[Bug]: Ruler moving speed

### ISSUE THREAD

**Issue by mannomannX** [LinwoodDev/Butterfly#480]
### What happened?

 Ruler movable with Hand-Tool, but doesn't move as fast as mouse curser

### Version

New nightly 2.0.0-beta.5

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed. When zoomed, the ruler moving speed is very slow

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.6
