### ISSUE TITLE
[Feature request]: Control mode "Touch" / "Mouse"

### ISSUE THREAD

**Issue by mannomannX** [LinwoodDev/Butterfly#481]
### Is your feature request related to a problem? Please describe

Controlling the tools

### Describe your feature request!

It would make life easier for Users who use their mouse, if there were optimized controls and hotkeys for dekstop users which might not be the same for Touch users. Best and only example that comes to mind is the new way of moving the tools in the toolbar or editing their parameters. We could make it be a simple and short right click to edit the parameters. Also hold-to-drag time could be shortened.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
There is now a "PlatformTheme" setting in the settings to change the context menus described in #410
