### ISSUE TITLE
[Feature request]: Sync with a local folder

### ISSUE THREAD

**Issue by Iey4iej3** [LinwoodDev/Butterfly#482]
### Describe your feature request!

It would be nice if it is possible to synchronize notes with a local folder. This is basically for Android, where the internal storage of the app is not accessible (without root access). One can then use Syncthing to synchronize notes on different devices without a cloud server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's sounds a bit complicated but I will look making it easier accessing the document directory outside of the app

**Comment by CodeDoctorDE** [comment]
I added a data directory setting in android where you can choose where all files are stored in 2.0.0-beta.7
