### ISSUE TITLE
[Documentation request]: license_ GPL-3.0-only or AGPL-3.0-only

### ISSUE THREAD

**Issue by jindam-vani** [LinwoodDev/Butterfly#492]
### To which page is your issue related?

https://github.com/LinwoodDev/Butterfly#butterfly

### Describe your documentation request!

@CodeDoctorDE 
* **GPL-3.0-only**
  * https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/dev.linwood.butterfly.yml#L3
  * img_ https://github.com/LinwoodDev/Butterfly#butterfly
 * **AGPL-3.0-only**
   * https://github.com/LinwoodDev/Butterfly/blob/develop/LICENSE
 * which is correct?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for your note.
MR created: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13685

**Comment by CodeDoctorDE** [comment]
What do you mean with img_ https://github.com/LinwoodDev/Butterfly#butterfly?

**Comment by CodeDoctorDE** [comment]
Fixed. Thanks for this note
