### ISSUE TITLE
[Feature request]: Offical macos support

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodDev/Butterfly#495]
### Is your feature request related to a problem? Please describe

MacOS can easily supported by fixing the ci build pipeline.
Currently the ci was disabled because of an error which I couldn't fix myself.

### Describe your feature request!

* Fix errors in the ci pipeline
* Reenable the build-macos step
* Add build dmg executable
* Add these artifacts in the release assets in the build ci

### Additional context

It would be cool if anyone who has a mac can create a pull request for this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DivineDominion** [comment]
@CodeDoctorDE  What's a CI build log with macOS still enabled to help figure out the problem?

**Comment by CodeDoctorDE** [comment]
Okay I recreated the flutter project and now the build works.
Can anyone look if the app works on mac?
Please login at github, click here: https://github.com/LinwoodDev/Butterfly/actions/runs/6224499158
And download the "macos-build" artifact

**Comment by CodeDoctorDE** [comment]
Okay, I will merge it now.
Then people can try it out and can give feedback

**Comment by Grunerd** [comment]
2.0.0.8 (nightly) crashes instantly on macOS 13.5.2 (MacBook Pro 16", M1 Max, 64GB):
[crashlog.txt](https://github.com/LinwoodDev/Butterfly/files/12676894/crashlog.txt)

**Comment by CodeDoctorDE** [comment]
Fixed
