### ISSUE TITLE
[Bug]: issues with markdown rendering

### ISSUE THREAD

**Issue by akberenz** [LinwoodDev/Butterfly#501]
### What happened?

The rendered markdown doesn't have expected formatting.

Take this as my text in a label element set to markdown mode
```
this *is* md

#### lists
- ~~buy cabbage~~
- change oil
- pet __cow__

and some `inline` block
```

I would expect it to be rendered as

> this *is* md
> 
> #### lists
> - ~~buy cabbage~~
> - change oil
> - pet __cow__
> 
> and some `inline` block

but instead it gets rendered as
> this *is*
> &nbsp;md
> #### lists
> ~~buy cabbage~~change oilpet **cow**and some `inline`
> &nbsp;block

This is consistent for both md written in the app and md imported in.

### Version

2.0.0-beta.8

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed. I will fix this in a hotfix update

**Comment by CodeDoctorDE** [comment]
I fixed the new line problems.
Feel free to create another issue to support lists in markdown. I'm currently not sure how to add customizability for this
