### ISSUE TITLE
[Bug]: Drawing is superslow

### ISSUE THREAD

**Issue by Temporalin** [LinwoodDev/Butterfly#503]
### What happened?

Hi! I was just trying this app and I noticed the last version in F-Droid (2.0.0-beta.9) can't hand-draw correctly.

With the pen tool selected, I swipe my finger on the screen and I need to wait a long time for the stroke to appear. I have installed the first version available (Versión 2.0.0-beta.7) and it works as expected, so I'm sure it's something recent.

I've tested it on LineageOS 20 on a OnePlus Nord and [Android 11/One UI 3.1] on a Samsung Galaxy Tab S5e

I can provide more information if necessary

### Version

2.0.0-beta.9

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I'm currently trying to find the version where this bug was introduced.
Can you try the 2.0.0-beta.8 version if the bug is also present there?
I tested it myself on windows and on my machine it works as expected.

**Comment by Temporalin** [comment]
It works fine in that version too

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.10
