### ISSUE TITLE
[Bug]: Scaling things with Rectangle Select tool distorts them

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#506]
### What happened?

Selecting multiple things and scaling them is supposed to scale everything in sync, as if it were one object. This may require moving internal elements around.
Instead, current Rectangle Select tool just scales each individual element around its own pivot point.

[scale.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/3e894259-4866-42b2-ae44-0c70c5d754a8)

### Version

2.0.0-beta.10 (F-Droid)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug reproducable! I will fix it

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.12.
It was `x * (y - 1)` (x = delta, y = scaling)
instead of `x - x * y = x * (1 - y)`.
