### ISSUE TITLE
[Enhancement]: Add trackpad gestures and ctrl +/- on windows

### ISSUE THREAD

**Issue by Aradig26** [LinwoodDev/Butterfly#507]
### Which feature is your request related to?

Scroll and zoom

### Describe your request for enhancements!

Would be great to scroll like that

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
What do you mean with fingers? This should already work.
Crtl +/- is on my todo list

**Comment by CodeDoctorDE** [comment]
I think you mean trackpad. I will add this to the next beta.
https://docs.flutter.dev/release/breaking-changes/trackpad-gestures

Feel free to create a new issue if you meant something different and this addition does not fix your problem. Please give more information if you open a new one.
