### ISSUE TITLE
[Bug]: massive grey screen when opening app

### ISSUE THREAD

**Issue by oorganic** [LinwoodDev/Butterfly#510]
### What happened?

opening the app after updating it leads to this screen: 
![Screenshot_20231025-181625_Butterfly Nightly_1](https://github.com/LinwoodDev/Butterfly/assets/148969094/cdbf914e-4607-43d7-a4e6-09555044df8a)

using lineageos on a samsung galaxy s5e

please let me know what other information is helpful to you

### Version

version 2.0.0-beta.11

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Oh yeah I fixed it some days ago, I will publish a hotfix on friday.
