### ISSUE TITLE
[Bug]: panning activates for all tools even with one finger

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#515]
### What happened?

For all tools, it pans the canvas around in addition to (trying) to use primary tool's function, just like if "hand" tool was also activated or both fingers were touched all the time.

It prevents any reasonable usage of Butterfly on this version.

~P.S. where is the web version now?~ ([found myself](https://butterfly.linwood.dev/), though some time ago it was not working)

[badpan.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/6f6a0928-7a13-4fa1-b96a-eb619ed71891)

### Version

2.0.0-beta.12 (F-Droid)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
oh yeah, I already fixed that in the 2.0.0-beta.13 hotfix.
The web version is at https://preview.butterfly.linwood.dev. I released this version on sunday, it should be updated on fdroid in a few days.
