### ISSUE TITLE
[Bug]: Multiple transformations using rectangle select tool produce bad results

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#517]
### What happened?

On https://preview.butterfly.linwood.dev/ drawing something, then using rectangle select tool, then doing more than one transformation tends to be buggy - it jumps back to previous version after releasing the mouse button.

Sometimes #506-like effect appears.

[badselect.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/177e5faa-6163-4903-a682-90f4205b8445)

### Version

No "current version" in "Settings -> General"

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
bug confirmed, thanks for reporting it

**Comment by vi** [comment]
Better, but rotating, then scaling is still poor:

[badselect2.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/34c39919-45dc-4651-bf89-74c8b80c7850)

**Comment by CodeDoctorDE** [comment]
Rotating is very new currently and it's not easy to make it compatible with all features of the app.
Can you make a new issue with all rotation issues? That would be nice. Then I can try to fix it one by one.
Without rotating, everything should work fine now.

**Comment by vi** [comment]
> Rotating is very new currently and it's not easy to make it compatible with all features of the app.

If you use [three-element coordinates `(x, y, scale)`](https://en.wikipedia.org/wiki/Transformation_matrix#Affine_transformations) instead of just `(x,y)` then rotations (and shears) should be as natural as scaling and translations - all those operations would be matrix multiplications.

**Comment by CodeDoctorDE** [comment]
That looks interesting, thanks I will look at it
