### ISSUE TITLE
[Bug]: Version number is not copyable from settings window

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#519]
### What happened?

"Settings -> General" now displays Butterfly version number, but it is not available for copying and pasting into bug reports.

### Version

2.0.0-beta.14

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's a good idea, i would call it enhancement.
On my list!

**Comment by vi** [comment]
More importantly, text in "text label" tool is also fails to be copied or pasted.

**Comment by CodeDoctorDE** [comment]
oh no, another bug...

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.14, feel free to create another issue for the missing copy and paste in the label tool
