### ISSUE TITLE
[Bug]: Text labels cannot be scaled

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#520]
### What happened?

Text labels can be moved, rotated and deleted using rectangle select tool, but cannot be scaled.

Also selection rectangle does not display handles initially, only after the first rotation.

[textnoscale.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/c1695cce-b678-44e2-9134-f34da5861731)

P.S. how do I edit text in already existing label?

### Version

2.0.0-beta.14

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I would classify it as enhancement but I will try implementing it!

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.14
