### ISSUE TITLE
[Bug]: Labelling feature doesn't accept input from bluetooth keyboard

### ISSUE THREAD

**Issue by oorganic** [LinwoodDev/Butterfly#522]
### What happened?

I'm on a Galaxy S5e tablet running LineageOS and I use a bluetooth keyboard. I can use the keyboard just fine throughout the app eg to name a file. I can even type in what size I want my label to be. But when I try to actually type the text I want into the label on the document, nothing happens. This is true both for text and for markdown. When I turn off my bluetooth keyboard & my OS keyboard pops up on my screen, I can use that to type just fine.

### Version

2.0.0-beta.12

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I added many new input features in the 2.0 update.
Can you try if this fixes your issue?

**Comment by CodeDoctorDE** [comment]
I close this issue since I got no response. Feel free to reopen this issue again if this issue appears again

**Comment by oorganic** [comment]
Hey, the text input now works but when I finish typing and go to another function the textbox disappears as if I never made it in the first place. Not sure if that's user error or a bug.

**Comment by CodeDoctorDE** [comment]
Which version do you use? It should be fixed in the latest nightly

**Comment by oorganic** [comment]
> Which version do you use? It should be fixed in the latest nightly

2.1.0-beta.5

**Comment by CodeDoctorDE** [comment]
Oh I changed it last week.
Then it should be fixed tomorrow :D
