### ISSUE TITLE
[Bug]: Export zip only contains notes which aren't in folders

### ISSUE THREAD

**Issue by oorganic** [LinwoodDev/Butterfly#523]
### What happened?

When I attempted to back up/export my notes using the tool in the app settings, the zip only contained my 3 notes which aren't organised into folders. No other notes or folders were in the zip. Samsung S5E, LineageOS

### Version

2.0.0-beta.12

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.14
