### ISSUE TITLE
[Bug]: S Pen stops writing and instead moves the board around.

### ISSUE THREAD

**Issue by GurrenLagann114** [LinwoodDev/Butterfly#529]
### What happened?

https://github.com/LinwoodDev/Butterfly/assets/145002867/e684e0e2-7590-4dc6-82f4-ca6040291ea0

When the pen is selected, it would often stop writing to instead move the board, even when the hand tool is *not* selected.
Selecting a different tool resets this issue but not always.

### Version

2.0.0-beta.15

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Seems like it registers the fast writing as scale gesture. I will look at this

**Comment by GurrenLagann114** [comment]
> I will try out something in the next beta. Can you look after the release of 2.0.0-beta.16 if this fixes the issue?

I'll look at it

**Comment by CodeDoctorDE** [comment]
The 2.0.0-beta.16 release was out, did it solve the issue?

**Comment by GurrenLagann114** [comment]
> The 2.0.0-beta.16 release was out, did it solve the issue?

It seems so, but I'll have to test the app longer though.

**Comment by CodeDoctorDE** [comment]
Okay thanks. I can explain what i did: I forgot to add a pointer cancel event (if the input was invalid) to unregister the pointer.
This meant that every time you canceled the pointer input, a new pointer was added to the list everytime and it had a count of more than 2.

**Comment by CodeDoctorDE** [comment]
Butterfly 2.0.0-rc.0 was released. If you found any other bugs feel free to report them.
