### ISSUE TITLE
[Feature request]: Support for Self-Signed Certificates

### ISSUE THREAD

**Issue by ahormann** [LinwoodDev/Butterfly#531]
### Is your feature request related to a problem? Please describe

I have a Nextcloud Server with HTTPS that uses a Self-Signed Certificate.
When I want to add a DAV remote to Butterfly 2.0.0-beta.15 i get a Handshake Error that states that the validation of the certificate failed.

### Describe your feature request!

Add a Checkbox in the Menu where you enter the URL and Login-Data for a new DAV Connection.
When it is checked Self-Signed Certificates are allowed.

### Additional context

Maybe this gets resolved with the Nextcloud-Support Ticket?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Self signed websites can be dangerous.
Do you want to disable certificate checking?

**Comment by ahormann** [comment]
I am talking about self hosted, so no danger here.
Exactly, some Option to say "I know this site may be dangerous, I trust it anyway".

**Comment by CodeDoctorDE** [comment]
I get the certificate when a bad certificate was recognized . We could make it more secure when saving the Sha1 when adding https://api.flutter.dev/flutter/dart-io/X509Certificate-class.html

**Comment by CodeDoctorDE** [comment]
This would be the last feature request I will add for the 2.0 stable. After this, I will add the next issues in 2.0.1 or 2.1

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/f009746b-8c43-48cf-b14b-d487775aae85)
Theoretically we could also allow certain certificates. What would be easier?

**Comment by ahormann** [comment]
Is this a question to me or to your fellow Devs?

**Comment by ahormann** [comment]
Oh okay. I am not sure how to understand the Question.
How would one define those certain certificates?
From a user perspective it would be easiest to have a toggle to ignore validation, but it's also easier to do accidentally when you use a dangerous server.

Alternatively Android allows for installing additional CA-Certificates, which some Apps just accept.
It is effort to install, but you only do it once per device and is less likely to be done accidentally. 

Is your idea to upload the certificate to the App?
This would be an uncommon choice, while I saw both of the above used successfully. It doesn't seem like something that should be handled per App.

**Comment by ahormann** [comment]
The Fingerprint is shown very weirdly (only special characters from foreign languages, the actual fingerprint is in the format A1:B2:D5:... (Only Hex numbers), but the connection works.
It does upload an empty Templates folder, but I did not manage to upload a file. Is there something I need to do to trigger the sync?

**Comment by CodeDoctorDE** [comment]
Hmm, theoretically it does it automatically. Maybe the sync code isn't working really good. I wrote it a year ago. If you want to have a reliably connection, the nextcloud sync app could work.

And I will look how I can improve the format

**Comment by ahormann** [comment]
Using the Nextcloud Sync App would be the best solution! But I don't get that to work either :/
When I use the Local option and use the Nextcloud folder it tells me /Documents/ is an Read-Only file System. It also fails to display a non-empty name.

I now also got a new Problem with the DAV connection:
"Bad state: No element". I can not add Elements (folders or files) either.

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-rc.0.
For me it works perfectly on a normal not-self signed server.
Please answer on this issue if you have any problems
