### ISSUE TITLE
[Documentation request] Improve explaination of input shortcuts

### ISSUE THREAD

**Issue by raffaem** [LinwoodDev/Butterfly#534]
### Which feature is your request related to?

S-pen

### Describe your request for enhancements!

I have an S-pen, I would like to activate the path eraser when I press the side button, and deactivate it when I release the side button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raffaem** [comment]
How do I find out "index where the path eraser is"?

**Comment by CodeDoctorDE** [comment]
You can customize the toolbar where the tools are stored. If you use `1` as input, it will be the first left tool on the toolbar

**Comment by raffaem** [comment]
I think the [docs](https://docs.butterfly.linwood.dev/docs/1.6/shortcuts#configure) are not clear on what a tool index is:

> Customize the controls by giving every control a painter index. The painter index starts at 1 and are ordered from left to right. An empty painter index will disable the painter switch on this control. Insert 0 to enable moving with this control.

"The 'painter index' of a tool is the position of the tool in the toolbar, with the leftmost tool having a 'painter index' of 1"

**Comment by CodeDoctorDE** [comment]
Yeah, it's always a bit tricky to explain something what seems clear for me.
I renamed painter to tools a few versions ago to help prevent confusion.
Thanks, I will change the docs to better explain what it does.

**Comment by CodeDoctorDE** [comment]
What do you mean with the pen button? Does it work with the stylus buttons?
Then I will call it "tool index" and try to improve the sentence a bit.
Do you mean the label tool here? I think we have already an issue here #522 but I'm currently struggeling reproducing the bug and fixing it then because I have currently no physical keyboards to connect to the phone. But I will try to fix this as soon as possible.

**Comment by CodeDoctorDE** [comment]
I changed it on the 2.0 version of the documentation.

**Comment by raffaem** [comment]
> What do you mean with the pen button? Does it work with the stylus buttons?

Sorry for the misunderstanding.

I mean the one and only button on the S-pen.

Apparently it's called "Pen button" in the settings.

> Do you mean the label tool here?

Yes

**Comment by CodeDoctorDE** [comment]
Maybe try the primary button but if it doesn't work it must be related to #270

**Comment by raffaem** [comment]
There is only one button on the S-pen. So Pen button, Stylus button, Primary button must refer to the same thing.

**Comment by CodeDoctorDE** [comment]
Yeah i think so. There are also stylus devices that have multiple buttons
