### ISSUE TITLE
[Bug]: Fullscreen broken for Android in 2.0.0-rc.0

### ISSUE THREAD

**Issue by droghio** [LinwoodDev/Butterfly#535]
### What happened?

Tried triggering fullscreen mode and nothing happened after pressing the button (menu and back button on Android still present). Switched to the 2.0.0-beta.7 and the button worked as expected (hides Android navigation bar).

Using a Kindle Fire 11 Max with Fire OS 8.3.2.1 (Android 11) if it helps.

### Version

2.0.0-rc.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by droghio** [comment]
Ran a quick test and full screen was working up to and including the 2.0.0-beta.15 but in the .16 the button has no effect for me.

**Comment by CodeDoctorDE** [comment]
Thanks, it's also reproducable on my phone.

**Comment by Luciogi** [comment]
The action in toolbar is working, but from dropdown menu it is not functioning

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.1
