### ISSUE TITLE
[Bug]: Full Screen button is not working on Android

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#536]
### What happened?

Full screen

https://github.com/LinwoodDev/Butterfly/assets/84625092/877c2396-2ee8-4be2-a9f6-cc5cdf9ffd8e

### Version

2.0.0-rc

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by droghio** [comment]
Wow fast respose! Will see if I can grab a screen capture. Either way ran a quick test and fullscreen was working up to and including the 2.0.0-beta.15 but in the .16 the button has no effect for me.

**Comment by Luciogi** [comment]
duplicate
