### ISSUE TITLE
[Bug]: Settings Ui suddenly goes to home screen

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#537]
### What happened?

https://github.com/LinwoodDev/Butterfly/assets/84625092/fb0d49f4-2a12-49c4-bd67-050013825044

# Expected
![Screenshot_20231203_090821](https://github.com/LinwoodDev/Butterfly/assets/84625092/55e55496-03e9-48f1-abf2-469c7183675d)

### Version

2.0.0-rc

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This was intentional but I could just change it if you want.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.1
