### ISSUE TITLE
[Bug]: "Zoom" toggle

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#538]
### What happened?

https://github.com/LinwoodDev/Butterfly/assets/84625092/5f7a0670-647f-4330-8145-868f8b98ef2a

Slider become invisible in fullscreen mode, but it stills function

### Version

2.0.0-beta.14

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luciogi** [comment]
Suggestion: On android it is not having slider on screen is useless, users are tend to use pinch gesture.
1. Disable zoom slider on android by default
2. Add toggle in settings

**Comment by CodeDoctorDE** [comment]
This is a feature. In full screen mode you should not distracted with other ui elements that are not relevant. Because of this only the toolbar is visible here.
The zoom slider can be toggled in Settings > Personalization > Zoom

**Comment by Luciogi** [comment]
> This is a feature. In full screen mode you should not distracted with other ui elements that are not relevant. Because of this only the toolbar is visible here. The zoom slider can be toggled in Settings > Personalization > Zoom

I thought it would disable zoom only

It should be renamed to "Zoom Slider", which is more descriptive

**Comment by CodeDoctorDE** [comment]
should i close this issue now or do you really need a zoom slider in full screen mode?
i wouldnt call the setting slider because its just a text field on mobile

**Comment by Luciogi** [comment]
> i wouldnt call the setting slider because its just a text field on mobile

Fine. Then add description for that toggle

**Comment by CodeDoctorDE** [comment]
Do you have a good description to that:
Zoom > The one in the bottom right corner

What I also can do: Limit the slider to a height > 500px. Then it will be changed to a text field that gets hide after 1 second

**Comment by CodeDoctorDE** [comment]
But it's not a slider on every resolution

**Comment by Luciogi** [comment]
@CodeDoctorDE in 2.0.0-rc `Settings > Personalization > Zoom` is not working :(

**Comment by CodeDoctorDE** [comment]
that's not good, thanks for reporting.
What about Zoom Floating Control?
It's not really an alternative zoom. It's just another control for the zoom level?

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.1
