### ISSUE TITLE
[Bug]: label tool: chinese/japanese text  input recognization issue

### ISSUE THREAD

**Issue by Yusei-StarDust** [LinwoodDev/Butterfly#539]
### Which feature is your request related to?

Label tool

### Describe your request for enhancements!

![butterfly_JoN2Ruiul6](https://github.com/LinwoodDev/Butterfly/assets/26076608/af9f6e9a-f233-49d2-8e5e-b6f76323c798)
don't know how to describe accurately so please check the screenshots
There is some  problems when inputting languages that require  romanization text conversion process.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I will look on this, thanks for reporting. I want to keep the 2.0 stable as bug free as possible.
Can you send me some example characters you typed so i can check it on my side?

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.1-rc.0
