### ISSUE TITLE
[Bug]: Area deletion is not rendered 

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#541]
### What happened?

1. Create Area
2. Hold on it
3. then select Delete from menu
4. Canvas does not update after deletion

### Version

2.0.0-rc

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting. I can reproduce it

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.1
