### ISSUE TITLE
[Bug]: Deleting small area is too difficult 

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#543]
### What happened?

First, tap and hold on reasonably large area is too slow to repond
For very very small area (which are drawn accidentally) are mostly impossible to delete

# Suggestion
- Make Area Removal tool like Path eraser

### Version

2.0.0-rc

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
There is no area remove tool.
Do you have a good idea integrating it in the area tool? I'm thinking about an area list view where you can see all areas and can remove them or a circle around your selection that you don't need to select the exact position
