### ISSUE TITLE
[Bug]: Area tool create small area using pinch to zoom

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#546]
### What happened?

A bug happened!

[area-tool-with-zoom.webm](https://github.com/LinwoodDev/Butterfly/assets/84625092/5adbdd99-9aee-40ef-8b50-7cd736b28a2e)

### Version

2.0.0-rc1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed, thanks for reporting!

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.2
