### ISSUE TITLE
[Bug]: performace is too bad on single page with alot of strokes

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#547]
### What happened?

# Video
https://github.com/LinwoodDev/Butterfly/assets/84625092/84fdf5ee-d7df-4544-9098-7f8213db2ce9

# Description
I was writing whole notes on single page, After a while, writing became laggy.

# Observations
1st stroke is drawing immediately, other srokes it takes seconds to draw

# Notes File
rename file to `export.bfly` then import in app
[export.bfly.zip](https://github.com/LinwoodDev/Butterfly/files/13631484/export.bfly.zip)

### Version

2.0.0-rc1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting.
Can you send me the document here (or privately at butterfly@linwood.dev) that I can test it on my side?

**Comment by CodeDoctorDE** [comment]
Thanks for reporting. I can reproduce this performance issue. It looks like it happens because the saving function takes too long

**Comment by GurrenLagann114** [comment]
I have to report that the problem is persisting on 2.0.0-rc2 version. After a writing a couple of lines it starts to lag a lot.

**Comment by CodeDoctorDE** [comment]
Hmm, I would start a new issue.
Performance issues can have multiple causes
