### ISSUE TITLE
[Bug]: changing pen style buttion is not noticable for user 

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#549]
### What happened?

A bug happened!

![Screenshot_20231215-192220_Butterfly Nightly](https://github.com/LinwoodDev/Butterfly/assets/84625092/1bbd56d4-0a27-479c-a1e1-44f13d6db08f)

### Version

2.0.0-rc1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yeah, that's intentional. You can create your own pen tool and customize it and this is just an icon for you to distinguish the tools in the toolbar

**Comment by Luciogi** [comment]
# Suggestion
1. For Android specific, from toolbar , when pen button is tap-n-hold other pen style should show
    a. It would have benefit that user do not need to create extra pens, and it is convenient to switch around
    b. It has just 2 step for changing pen style
![mockup-pen](https://github.com/LinwoodDev/Butterfly/assets/84625092/068a45dc-1d2b-4c6d-8ed2-3a28de3c7eac)

2. 2nd option, make a visible change in existing layout, a small drop down icon and accent colored box around icon
    a. Users would might struggle with this design for switching
    b. Make more tools icons (fountain pen, pointer, hi-lighter) inside add button of toolbar
![pen-drop-menu](https://github.com/LinwoodDev/Butterfly/assets/84625092/b1953a39-0069-4ead-8ce4-083ef370bd25)

**Comment by CodeDoctorDE** [comment]
I added a tooltip that shows "Icon" to clarify it a bit in 2.0.0-rc.2

**Comment by CodeDoctorDE** [comment]
The first option can't be used, hold is for moving tools and opening property views and if you don't change icons very often and you will often change the icon only if you change the properties in the properties view.
I will try to implement the second option

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/cf0da612-4b4a-4364-b53e-b51c8021236d)
Would this help?
> Make more tools icons (fountain pen, pointer, hi-lighter) inside add button of toolbar

What do you mean with this? Like I said, it doesn't change the behavior of the tool. It's just for users that wants to see the difference between the added tools

**Comment by Luciogi** [comment]
> ![image](https://private-user-images.githubusercontent.com/20452814/290855472-cf0da612-4b4a-4364-b53e-b51c8021236d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTQxMjMsIm5iZiI6MTcwMjY1MzgyMywicGF0aCI6Ii8yMDQ1MjgxNC8yOTA4NTU0NzItY2YwZGE2MTItNGI0YS00MzY0LWI1M2UtYjUxYzgwMjEyMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE1MjM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZGZhOTViNGI2YjIxZjZmYTY4Mzc1ODQ2OGI2OGQyNGI4ZDhiNTBmNjQzYzk1Y2FlOTEzYzhjYmE5N2ZjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3sjgkJ7N82bPvhvkV4V3Nt7ixHywCBLL4d5TGZ1xlbw) Would this help?
yes it is good
