### ISSUE TITLE
[Bug]: On android, pressing back button closes Butterfly app

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#551]
### What happened?

When using back gesture, inside note canvas , app exits.
It should go to home, and from home use double back should exit
https://github.com/LinwoodDev/Butterfly/assets/84625092/14fac874-0391-4d75-b6fe-0005803af953

### Version

2.0.0-rc2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed. Thanks for reporting!

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-rc.3
