### ISSUE TITLE
[Bug]: duplicate button for selection need better icon

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#552]
### What happened?

A bug happened!
![Screenshot_20231216-112523_Butterfly Nightly](https://github.com/LinwoodDev/Butterfly/assets/84625092/d06063b6-d5e8-4f26-861f-5008646187a5)

"duplicate" and "copy" buttons have same icon

duplicate can look like 
![image](https://github.com/LinwoodDev/Butterfly/assets/84625092/8a8f78a9-dceb-4db8-b860-c2fdb04b5b9b)

### Version

2.0.0-rc2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea.
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/0ea1524d-2cae-4e42-900a-38a9164d02ee)
I use the phosphor icons family.
I found a similar icon. What do you think about it?

**Comment by Luciogi** [comment]
## Duplicate icon
![image](https://github.com/LinwoodDev/Butterfly/assets/84625092/5a7ac990-31fb-4e0a-9aa2-1f06d2379336)

## Copy icon
![Screenshot_20231216_131839](https://github.com/LinwoodDev/Butterfly/assets/84625092/0815aae1-3c0e-45d5-97ac-233d968c3454)

**Comment by CodeDoctorDE** [comment]
i saw it, did you have a good icon which i could alternatively use from the phosphor icons family: https://phosphoricons.com

**Comment by CodeDoctorDE** [comment]
But i don't see a real solution here. The icons are too similar

**Comment by Luciogi** [comment]
other icons does not fit here

**Comment by CodeDoctorDE** [comment]
Changed in 2.0.0-rc.3. Thanks for the suggestion
