### ISSUE TITLE
[Bug]: Mac — Can't save files to profile document folder.

### ISSUE THREAD

**Issue by trmendes** [LinwoodDev/Butterfly#558]
### What happened?

It seems that the app Documents folder lives inside the app container, and I'm not able to change it.

1) Change the document folders and select it to be the document folder inside my profile folder
2) Close the app
3) Open the app

— What I'm getting.
An error message telling me butterfly have no access to that specific folder.

— What I expect
To be prompt by the system and give butterfly access to that specific folder
To open butterfly and be able to load and save files to a folder outside the container.

# Extra note

Platform is Mac and not Android (as selected)

### Version

2.0.0.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I have no mac so I cannot test it.
Can you show me the error message? On macos the directory picker will be spawned with osa script.

**Comment by CodeDoctorDE** [comment]
After 2.0.0, I will switch the file_picker lib to https://pub.dev/packages/file_selector.
Then we can look if this fixes the problem

**Comment by CodeDoctorDE** [comment]
Can you test this build once it was built? https://github.com/LinwoodDev/Butterfly/actions/runs/7275225848

**Comment by trmendes** [comment]
It failed to deploy

**Comment by trmendes** [comment]
<img width="794" alt="Screenshot 2023-12-20 at 22 52 20" src="https://github.com/LinwoodDev/Butterfly/assets/16507629/4565f645-8ff8-449a-bf54-3a9d2372f14d">

**Comment by CodeDoctorDE** [comment]
Oh, I think I fixed it in the next build. Can you try it once it built? https://github.com/LinwoodDev/Butterfly/actions/runs/7281200280

**Comment by trmendes** [comment]
Sure. Just did it but the issue is still there. Same message as the screenshot above.

**Comment by CodeDoctorDE** [comment]
Hmm,
Then I don't know what I can do.
Has this documents directory the right permission?

**Comment by CodeDoctorDE** [comment]
Oh I have an idea: Try to reset the data path and reselect it again.
Maybe it needs to use the new dialog to select the directory.

**Comment by CodeDoctorDE** [comment]
I close this issue since I got no response. Feel free to reopen this issue again if this issue appears again
