### ISSUE TITLE
Data directory can't be changed

### ISSUE THREAD

**Issue by pr1mee** [LinwoodDev/Butterfly#562]
### What happened?

When changing data directory nothing happens.
Will send video if needed.

Android 13 / miui14 / Xiaomi 13T Pro and Xiaomi Pad 6

### Version

2.0.0

### Platform

Android

### Relevant log output

```shell
Where to log? Didn't have error codes or smth
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
bug confirmed and fixed!
