### ISSUE TITLE
Amoled theme 

### ISSUE THREAD

**Issue by Zaxx69** [LinwoodDev/Butterfly#564]
### Describe your feature request!

Pure black theme 

### Additional context

![Screenshot_2023-12-28-17-55-51-93_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/LinwoodDev/Butterfly/assets/138523882/bc357cc0-0a74-4044-ae77-61175453d350)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Added in 2.0.1-rc.0

**Comment by Zaxx69** [comment]
Thanks
