### ISSUE TITLE
[Bug]: Remote connection from http WebDav

### ISSUE THREAD

**Issue by trya2l** [LinwoodDev/Butterfly#567]
### What happened?

Hi,

I've set up a WebDav server with Apache, but currently, I do not have access to ssl.

I think because of this, I cannot connect butterfly to it.

![Screenshot from 2024-01-03 20-35-14](https://github.com/LinwoodDev/Butterfly/assets/79646756/6ce938b7-9267-4407-8d35-b318045e8fda)

### Version

2.0.0

### Platform

Linux

### Relevant log output

```shell
Error while creating connection
Cannot connect
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, can you test if this url works in your browser?
In the code it just creates a get request with the authorization header https://github.com/LinwoodDev/Butterfly/blob/develop/app/lib/settings/connections.dart#L220

**Comment by trya2l** [comment]
Thanks for the answer, I didn't allow an access through the browser, so it may be on my side. (Sorry, I am not familiar with webdav)

**Comment by CodeDoctorDE** [comment]
Generally the server does not need to answer on a get request by spec but I added it to verify the server is running

**Comment by trya2l** [comment]
Ok, that was the reason. Thanks.

However, I still have a little issue.
The connection in now establish, but the directory keeps loading, and I cannot  create new files.

![image](https://github.com/LinwoodDev/Butterfly/assets/79646756/e708d8b5-3008-4eef-8fc9-81403208e9c3)

In my dav, I see the new directories (doc, templates, packs) but I cannot create a file.

Once again, it may be due to my configuration, but I can't figure out what is lacking.

Have you already seen an issue like this ?

**Comment by CodeDoctorDE** [comment]
Hmm,
are you sure you have a real webdav server there?
It just uses the methods in the webdav specs.
To fetch the things, butterfly runs `PROPFIND` on the url

**Comment by trya2l** [comment]
It should be real, but badly configured ^^' 
I did not configured PROFIND the URL, so I will go back to correct it.
Thanks.

**Comment by trya2l** [comment]
Hi (erm, sorry for reopening the issue)

Finally, I did not succeed, even with `PROPFIND` activated.

I may be able to find a solution, but apparently, there is a trouble with the `Depth: infinity` property in the header. This time, I am not sure it is on my side. What do you think about it ?

```sh
$ curl --request PROPFIND --location 'http://myserver.dav/webdav/butterfly/Templates?' --user user:pass
```
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>PROPFIND requests with a Depth of "infinity" are not allowed for /webdav/butterfly/Templates/.</p>
<hr />
<address>Apache Server at myserver.dav Port 80</address>
</body></html>
```

**Comment by CodeDoctorDE** [comment]
Hmm, I have currently no idea.
I use 
```dart
createBaseRequest(remote.buildTemplatesUri(path: ""),
          method: "PROPFIND");
```
for the request. It would be better if you can join the matrix/discord server so we can look at your specific setup. I think this thread would get very long if we continue here on github.

**Comment by trya2l** [comment]
Ok, I will do as you say. Thanks
