### ISSUE TITLE
[Enhancement] Restrict drawing over selected area

### ISSUE THREAD

**Issue by markwmuller** [LinwoodDev/Butterfly#573]
### Is your feature request related to a problem? Please describe

I do not have a personal use case for an infinite canvas, and indeed this makes the app harder for me to use

### Describe your feature request!

I like my digital notes to be somewhat like my paper notes; constrained to A4 (or letter) size pages. These are ideally portrait oriented, and vertically scrollable (i.e., the top of the next page starts just under the bottom of the previous page). 
These notes can then be exported to a PDF, and e.g. printed out. 

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I don't want to have 2 different types of notes, because of this there are "Areas" in butterfly.
Add a area tool to your toolbar, set the aspect ratio to landscape/portrait and start drawing your constraints. Right click the area and click on "Enter area" to only see this area.
Is that what you are looking for?

**Comment by markwmuller** [comment]
I don't know how to right-click on Android, but I don't think this is what I'm looking for exactly (although it might be a clunky work-around, in which case maybe this app is just different from what I want). 

Background on my use cases: 

For me, conceptually, my digital notes are on pages, and the pages are "sorted" so that older info is at top, and time/ideas proceed/proceed downwards. Having a default size helps me keep things neat, my tablet is roughly the size of a piece of paper, so that width makes sense). 

Moreover, I use my tablet to lecture (projecting the tablet display), and then I save the resulting notes as PDF to distribute to students. I currently do this using [Xodo PDF](https://play.google.com/store/apps/details?id=com.xodo.pdf.reader), where I annotate a blank PDF, which then is exported to PDF. However, I'd love an open-source tool. 

I used to use [Xournal++,](https://github.com/xournalpp/xournalpp) but that doesn't work on android. (Xournal++ on a PC is my platonic ideal of a stylus-enabled tool).

Saber does much of what I want, but I don't want an app that uses a mysterious back-end storage system (even if it is my own nextcloud). I want local files, I can take care of syncing local files myself across my devices (and then I can take care of backups, etc, just like I do with any other important files I have). 

Anyway, I realize you're not getting any money from me, so thank you for listening to my request.

**Comment by CodeDoctorDE** [comment]
It's long clicking on mobile.
I will add a setting in the pdf import to automatically create areas for every page. This should improve the workflow for pdfs.
In the 2.1 update, I will add an extra areas view where you can see all your areas alphabetically and can edit/export/delete them. This way you can organise your areas very easily.
For me, it isn't very nice to have two different types of pages in an app. This will add complexity and I don't really see a downside to the area feature.
It is not the traditional type of "pages" or grouping, but I think you get in very quickly.

Yes, I'm doing this in my free time and don't get any money. But I'm always happy when my app helps people in their lives as much as it does mine.

**Comment by markwmuller** [comment]
Got it, I didn't understand the area icon for "entering" (though, in retrospect, I don't know how one would make it clearer). Maybe the overlap with the "export" button is what threw me? 

 Tried it now, and I'm not sure I understand the areas workflow. When I'm in the area, my strokes are restricted to be within them. But when I exit the area, the strokes that left the area (or were drawn wholly oustide the area) are there. It seems like the area tool just restricts what I can see, and not where I can write? Apologies if I'm being obtuse and missing something obvious!

**Comment by CodeDoctorDE** [comment]
Hmm maybe I put enter area as first item?

Yeah this is intentional. But in retrospective it seems useful that pen strokes will also be restricted while drawing.
Now I'm thinking, should also be the shape tool restrictive? Sounds logical

**Comment by CodeDoctorDE** [comment]
I created a new issue #574 to split this into two milestones.
In 2.0 I will add the restriction, in 2.1 I add the area navigator page.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.2-rc.0
