### ISSUE TITLE
[Documentation]: Can't tell if getting nightly or stable on f-droid

### ISSUE THREAD

**Issue by markwmuller** [LinwoodDev/Butterfly#576]
### What happened?

On f-droid / fdroid, there are two versions of butterfly. One is the stable (I think), and one is nightly. It's very hard to tell which is which, except by going to the "versions" tab of f-droid, and looking if it shows "RC".

### Version

2.0.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yeah I know this but I don't find a solution to this.
Both pages are linked to the same github repository where fdroid looks in the fastlane directory.
If you or anyone else has a fix/solution for this and is familiar with the fdroid system, feel free to make a pr or answer here.

**Comment by CodeDoctorDE** [comment]
Related to https://gitlab.com/fdroid/fdroidserver/-/issues/829#note_1471208594 maybe.

@IzzySoft, does it work on my current repo too? The update.py link currently links to the donate function, this doesn't look right. Did you have any repo that already includes flavors without gradle?

**Comment by IzzySoft** [comment]
Can you tell me what repo you mean? Going by the link above I assume you mean F-Droid.org, where I'm currently [not active at](https://gitlab.com/fdroid/admin/-/issues/447). I have no `update.py` links at IzzyOnDroid AFAIK, so I have no idea what you want me to check, sorry. Following the link to the fdroidserver issue: Well, that's F-Droid.org. IzzyOnDroid operates differently, the fastlane root to be used is configured with each app's metadata here.

**Comment by CodeDoctorDE** [comment]
Oh sorry I didn't know that. I only saw you commented on this issue and want to ask what you linked there. Then I need to see who I can reach to help me.

**Comment by IzzySoft** [comment]
Best luck! I recommend opening an issue [at their fdroiddata repo](https://gitlab.com/fdroid/fdroidserver/-/issues), the fdroiddata team (especially linsui and Licaon) will certainly help you.

**Comment by CodeDoctorDE** [comment]
should be fixed in 2.1.0-rc.1 if it will be deployed on fdroid
