### ISSUE TITLE
Add page notes 

### ISSUE THREAD

**Issue by Nawo-pingu** [LinwoodDev/Butterfly#577]
### Describe your feature request!

Instead of using the infinte canvas, I would like to be able to write pages notes.

### Additional context

I would make the app more polyvalent and thus used since writing pages are a must for a note app. 
Also exporting a note would be easier since we won't have to select the area in an infinite canvas which is often a page shape

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I think this is related to https://github.com/LinwoodDev/Butterfly/issues/573
I don't like having two different types of documents in an app. Then I would split it into two different apps.
But...,
I will try to make the area feature more accessible and easier to use with a new area navigator page (see #574).
If you have other ideas how to enhance the area feature, feel free to answer me here.
