### ISSUE TITLE
[Feature request]: Add shape detection for free hand

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#578]
### Describe your feature request!

I think the app should have a feature that when the line is drawn it automatically becomes straight if you stay still for a certain time with the pen pressed. It would be faster than using the ruler, which is still a useful tool. I like how it is implemented in onenote. I could try to take care of this. I would like to offer my contribution.

### Additional context

It is very convenient for example if you draw electrical circuits or anything else where you want to have a fast but not too precise workflow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for creating the issue. I've added a title to the issue to organize it better.
I thought about the idea too. Do you think it should be its own tool, or should it be a property of the pen tool?

**Comment by MrGumpIT** [comment]
I see it more as a property, maybe activatable or not. As a tool, the ruler is already available

**Comment by CodeDoctorDE** [comment]
Okay,
thanks for the feedback. I will try to implement it in the future (maybe 2.1?)

**Comment by MrGumpIT** [comment]
Okay, thanks to you I find Butterfly to be a great app. I’m not a pro, but if there’s anything I can help you with, let me know

**Comment by CodeDoctorDE** [comment]
Thanks,
I welcome every contribution. Some things where you can help me:
* Spread the app to the world. If you think a person needs a app like this, feel free to suggest it to them
* https://github.com/LinwoodDev/Butterfly/labels/good%20first%20issue are good issues if you are familiar with flutter or fdroid
* Expanding the documentation. If you find something missing in the documentation, feel free to edit them and make a pull request. More information here: https://docs.butterfly.linwood.dev/contributing#write-documentation
* Translate the app: https://translate.linwood.dev/butterfly
