### ISSUE TITLE
[Feature request]: custom resizeable toolbar & multiple columns and multi row supported toolbar 

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#589]
### Is your feature request related to a problem? Please describe

I can't fit all tools in single page without scrolling it

Thanks 

### Describe your feature request!

Settings to trigger custom toolbar sizes & multi column support 

### Additional context

OS: Android 11 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's sounds good. Do you have any design ideas how to do it?
I'm thinking about tabs where you can have grouped your tools but you needs much space for this

**Comment by HusniMuhammad** [comment]
> That's sounds good. Do you have any design ideas how to do it? I'm thinking about tabs where you can have grouped your tools but you needs much space for this

By the way  I'm mistakely understand columns I means by that 
Multi line && multi column


![Screenshot_20240211-173335](https://github.com/LinwoodDev/Butterfly/assets/104101867/e4c2f544-7056-41a5-be7e-16b1885562ea)


![Screenshot_20240211-172344](https://github.com/LinwoodDev/Butterfly/assets/104101867/516ed5f3-eea1-4451-b954-56810e3b2c43)



This is screenshort of toolbar used by NMM
[NMM file manager & text editor](https://play.google.com/store/apps/details?id=in.mfile)

**Comment by CodeDoctorDE** [comment]
Hmm are you sure you want to have multiple columns instead of grouping? When having multiple columns it can get very big like the old toolbars on internet explorer.

**Comment by HusniMuhammad** [comment]
> Hmm are you sure you want to have multiple columns instead of grouping? When having multiple columns it can get very big like the old toolbars on internet explorer.

Yes I want it.
it can be enabled by the settings of **butterfly** app so this option disabled by default (it's your choice)
Also it can be fit into the screen (like keyboard layout fit into the screen)

**Comment by CodeDoctorDE** [comment]
Okay, I could add it.
Then we could have this layout:
|||
| - | - |
| 1 | 3 | 5 |
| 2 | 4 | 6 |

Then I would add small (75% the size), normal (100% the size) and big (125% the size) as option.

I'm still thinking about adding grouping support in butterfly to help people organize their tools. Do you have any ideas how we could comine this?

**Comment by HusniMuhammad** [comment]
> Okay, I could add it. Then we could have this layout:
> 
> 1	3
> 2	4
> Then I would add small (75% the size), normal (100% the size) and big (125% the size) as option.
> 
> I'm still thinking about adding grouping support in butterfly to help people organize their tools. Do you have any ideas how we could comine this?


Ok thanks for improvement

**Comment by CodeDoctorDE** [comment]
> > Okay, I could add it. Then we could have this layout:
> > 1	3
> > 2	4
> > Then I would add small (75% the size), normal (100% the size) and big (125% the size) as option.
> > I'm still thinking about adding grouping support in butterfly to help people organize their tools. Do you have any ideas how we could comine this?
> 
> Ok thanks for improvement , also having grouping options with customize the number of tools
> 
> Also add a option to How many items can be viewed without scrolling (horizontally/vertically)

Yeah but how?
![grafik](https://github.com/LinwoodDev/Butterfly/assets/20452814/b2531a02-cf2e-4947-a985-a74e14e46cbd)
I could add a new icon button that opens the toolbars change menu like with the lock button.
I would add it like you can select how many rows there are and make it responsive like this:

with 2 rows:

with 3 rows:

|||
| - | - |
| 1 | 4 | 
| 2 | 5 |
| 3 | 6 |


|||
| - | - |
| 1 | 3 | 5 |
| 2 | 4 | 6 |


(the numbers are the indexes of the tools)

**Comment by HusniMuhammad** [comment]
Ok this way better,

(number of  row)=(number of tools)÷(number of columns displayed by specific device/orientation),

**Comment by HusniMuhammad** [comment]
> Hmm are you sure you want to have multiple columns instead of grouping? When having multiple columns it can get very big like the old toolbars on internet explorer.

Quick access is the main motivate

**Comment by HusniMuhammad** [comment]
Hi,When will be fixed this issue?

**Comment by CodeDoctorDE** [comment]
Soon 🔜. Before the first release candidate of 2.1.
I currently don't have much time working on this right now. Maybe in a few weeks?

**Comment by CodeDoctorDE** [comment]
I added configurable toolbar size in 2.1.0-beta.3 (should be released soon).
Multi column will be next

**Comment by CodeDoctorDE** [comment]
![grafik](https://github.com/LinwoodDev/Butterfly/assets/20452814/80137029-6a75-4e95-958e-22e8c172998c)
I'm currently testing a bit out and it looks promising

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-beta.4 :)
