### ISSUE TITLE
[Feature request]: add export option in toolbar

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#590]
### Is your feature request related to a problem? Please describe

Quick access 

### Describe your feature request!

![image3](https://github.com/LinwoodDev/Butterfly/assets/104101867/668be9c0-b56b-4dae-b585-7e45e00c6562)

### Additional context

Android 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea but maybe we should add a pin button on the export dialog instead?

**Comment by HusniMuhammad** [comment]
> Good idea but maybe we should add a pin button on the export dialog instead?

📌 Meaning?

**Comment by HusniMuhammad** [comment]
> > Good idea but maybe we should add a pin button on the export dialog instead?
> 
> 📌 Meaning?

I think means (specific or unchangable)

I think it's called **badge**

**Comment by CodeDoctorDE** [comment]
Fixed 5 issues today 🎉 Added in 2.1.0-beta.0

**Comment by HusniMuhammad** [comment]
> Fixed 5 issues today 🎉 Added in 2.1.0-beta.0

I downloaded the mentioned version 2.1.0-beta.0

Not showing any new features

![Screenshot_20240303-081439](https://github.com/LinwoodDev/Butterfly/assets/104101867/9deee79e-320c-4ec1-9a95-aacb744ade22)
![Screenshot_20240303-081622](https://github.com/LinwoodDev/Butterfly/assets/104101867/a8b1e2cc-2bf5-4a32-a82a-ff4e405aee5a)

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/878bd359-fd81-4fb4-bef2-6927f8d05a99)
Click on Export -> Image
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/963d3555-1041-427d-b04f-212dce612d69)
And then on pin
