### ISSUE TITLE
[Enhancement]: butterfly saves progress automatically. IS this reduces performance?

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#591]
### Which feature is your request related to?

Automatically saves 

### Describe your request for enhancements!

 butterfly saves progress automatically. IS this reduces performance?

Or Manually add save button (asking)

### Additional context

Android 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Maybe a bit, I will add a function to disable autosave

**Comment by CodeDoctorDE** [comment]
Fixed in https://github.com/LinwoodDev/Butterfly/commit/68bc35c3df1afe1b815be2b35923be583779a860 in 2.0.3-rc.1.
