### ISSUE TITLE
[Bug]:  form asking useless names/text

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#592]
### What happened?

When I double tab (to remove specific tool from toolbar ) it's asking name 
![image4](https://github.com/LinwoodDev/Butterfly/assets/104101867/a6a8a58c-9302-4eb8-b710-af6c816d9412)

 form asking useless names/text

### Version

2.0.2 (from f-droid )

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Here you can change the tooltip of the tool

**Comment by HusniMuhammad** [comment]
> Here you can change the tooltip of the tool

I don't I understand please elaborate

**Comment by CodeDoctorDE** [comment]
![grafik](https://github.com/LinwoodDev/Butterfly/assets/20452814/d6edd056-c7f6-4818-a1fd-3b25cd7bb4a4)
If you hover on the tool you get the name of it

**Comment by HusniMuhammad** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/20452814/303932594-d6edd056-c7f6-4818-a1fd-3b25cd7bb4a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Njk2NzMsIm5iZiI6MTcwNzY2OTM3MywicGF0aCI6Ii8yMDQ1MjgxNC8zMDM5MzI1OTQtZDZlZGQwNTYtYzdmNi00ODE4LWExZmQtM2IyNWNkN2JiNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE2MzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDg2MGVmMmYzZDg4NGI4ZThlYTY5NDU3OWM1ZmYzZjNiZjY1NGRhMDNlZjk3Y2Q0MTYyNzY1YmMwNmRhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UP3Rb4OroORoJsqco6b1t0M1r2jR9xA2DyBFZFir9Rs) If you hover on the tool you get the name of it

That means 

> ![grafik](https://private-user-images.githubusercontent.com/20452814/303932594-d6edd056-c7f6-4818-a1fd-3b25cd7bb4a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Njk2NzMsIm5iZiI6MTcwNzY2OTM3MywicGF0aCI6Ii8yMDQ1MjgxNC8zMDM5MzI1OTQtZDZlZGQwNTYtYzdmNi00ODE4LWExZmQtM2IyNWNkN2JiNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE2MzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDg2MGVmMmYzZDg4NGI4ZThlYTY5NDU3OWM1ZmYzZjNiZjY1NGRhMDNlZjk3Y2Q0MTYyNzY1YmMwNmRhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UP3Rb4OroORoJsqco6b1t0M1r2jR9xA2DyBFZFir9Rs) If you hover on the tool you get the name of it

What's the point on that?

**Comment by CodeDoctorDE** [comment]
It should help you to distinguish it better if you have multiple pens. Do you have a better idea for this?

**Comment by CodeDoctorDE** [comment]
Okay can I close this issue?

**Comment by HusniMuhammad** [comment]
> Okay can I close this issue?

Wait

**Comment by HusniMuhammad** [comment]
> It should help you to distinguish it better if you have multiple pens. Do you have a better idea for this?

Why even undo redo having these
![Screenshot_20240212-032849](https://github.com/LinwoodDev/Butterfly/assets/104101867/c5f3c47e-3fe9-4838-bbe7-a1c1e8e6a8ac)

**Comment by CodeDoctorDE** [comment]
It should be consistent for all tools.
Maybe I will add more properties for these tools in the future (for example how many undos you can do, which things gets undo, ...)

**Comment by HusniMuhammad** [comment]
> It should be consistent for all tools. Maybe I will add more properties for these tools in the future (for example how many undos you can do, which things gets undo, ...)

0k

**Comment by HusniMuhammad** [comment]
> Okay can I close this issue?

Ok
