### ISSUE TITLE
[Enhancement]: Differentiate between page color and background color 

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#593]
### Which feature is your request related to?

Differentiate between page color and background color 

### Describe your request for enhancements!

![Screenshot_20240211-212735](https://github.com/LinwoodDev/Butterfly/assets/104101867/22815908-0753-4cc1-a532-ce399526ef5e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
What do you mean with page color and background color?

**Comment by HusniMuhammad** [comment]
> What do you mean with page color and background color?


Is it true all the screen is the page?

Then no background; that means no background color!

**Comment by CodeDoctorDE** [comment]
I currently don't know what you mean.
The page itself is the whole canvas you use. You can add a new one in the pages navigator page

**Comment by HusniMuhammad** [comment]
> I currently don't know what you mean. The page itself is the whole canvas you use. You can add a new one in the pages navigator page

I initially thought everypage have sizes (so it can have background) know I understand

**Comment by CodeDoctorDE** [comment]
No, it's an infinite canvas like onenote but better :)
