### ISSUE TITLE
[Enhancement]: Export whole page 

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#594]
### Which feature is your request related to?

Export whole page not what screen fit into image

### Describe your request for enhancements!

Export whole page 

### Additional context

Android 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, we could add a "Fit whole page" button on the export button to change the rectangle of exporting

**Comment by HusniMuhammad** [comment]
> Hmm, we could add a "Fit whole page" button on the export button to change the rectangle of exporting
Ok

**Comment by CodeDoctorDE** [comment]
Fixed 5 issues today 🎉 Added in 2.1.0-beta.0
