### ISSUE TITLE
[Feature request]: after export to image(etc) trigger/not trigger android share intent (users choice)

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#595]
### Is your feature request related to a problem? Please describe

Every time exporting asking to sharing 

### Describe your feature request!

Settings > Don't share after export [checkbox] [true/false]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
What should be do instead of sharing?

**Comment by HusniMuhammad** [comment]
> What should be done instead of sharing?

Saving the file into local directory allowed in Android 11/Android 12

**Comment by CodeDoctorDE** [comment]
I think this isn't really good.
You should be able to share your notes with everyone else. Tools will be saved on the document itself and if we save it in the document the path could be invalid on some other device

**Comment by HusniMuhammad** [comment]
> I think this isn't really good. You should be able to share your notes with everyone else. Tools will be saved on the document itself and if we save it in the document the path could be invalid on some other device

Ok 👍 I understand, feature request cancel
