### ISSUE TITLE
[Bug]: F-droid website's search results showing two different types of **butterflies**

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#600]
### What happened?

For **Android** build 
F-droid website's search results showing two different types (signatures) of **butterfly** [f-droid search](https://search.f-droid.org/?q=Paint&lang=en)

![Screenshot_20240212-115803](https://github.com/LinwoodDev/Butterfly/assets/104101867/898a32ab-8977-4ea3-8cbb-da54d7b47884)

**Android**

### Version
2.0.2
### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's intentional. There is one for nightly and one for stable.
There is already one issue that they have the same name, see #576.
I would call this a "documentation request" because it isn't related to the app itself.
