### ISSUE TITLE
[Enhancement]: add keyboard shortcuts for pen and eraser

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#603]
### Which feature is your request related to?

keyboard shortcuts

### Describe your request for enhancements!

Flutter does not support Windows Ink, and graphics tablets work in either mouse mode or Windows Ink mode. In mouse mode you cannot use the pen keys. It would be useful to have keyboard shortcuts for the pen and eraser so that they can be associated via the graphics tablet's proprietary software

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
There are already shortcuts:
ctrl + 1 => 1st tool
ctrl + 2 => 2nd tool
...

I can't assign shortcuts to specific tools because you can simply move them around
