### ISSUE TITLE
[Enhancement]:Invert PDF colors if the background is dark and text pdf is black

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#606]
### Which feature is your request related to?

pdf import

### Describe your request for enhancements!

If you import a PDF with a dark background, the PDF is not readable
![image](https://github.com/LinwoodDev/Butterfly/assets/47901429/2ef790b1-2a0a-496f-b8e1-08dcb203ebe2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Looks like the pdf has a transparent background. We could add new pdf options:
* Add white background
* Invert image
