### ISSUE TITLE
[Enhancement]: Move rotation button to the top

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#607]
### Which feature is your request related to?

Selection

### Describe your request for enhancements!

Currently, To rotate object user need to drag center of object, and to move drag on non centre part of object
For smaller object, it is not easy to touch and drag non centre part

## Suggestion
When object is selected, default mode should be "move"
when users tap/click on selected object it should activate "rotate" mode

Move scaling object with respect to skew and locked aspect ratio to separate tool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luciogi** [comment]
> I think a separate tool isn't very good because it's overcomplicated it and if we have this new selection system on the area too, we need to have 4 different tools

As far I saw, after testing area tool, it does not have rotate and scaling
So, with above suggestion, there would be 
- Selection Tool (that can move and rotate round objects)
- Scaling Tool

**Comment by CodeDoctorDE** [comment]
Hmm, I don't want to create more tools than nessesary. I don't see a big problem having everything in once.

An alternative could be changing the rotation system to the one in office 365:
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/e4b4f23d-82b5-46eb-aae6-4c9295404b41)
The rotation button here is at the top of the selection

**Comment by Luciogi** [comment]
> Hmm, I don't want to create more tools than nessesary. I don't see a big problem having everything in once.
> 
> An alternative could be changing the rotation system to the one in office 365: ![image](https://private-user-images.githubusercontent.com/20452814/306596344-e4b4f23d-82b5-46eb-aae6-4c9295404b41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTU0NzgsIm5iZiI6MTcwODUxNTE3OCwicGF0aCI6Ii8yMDQ1MjgxNC8zMDY1OTYzNDQtZTRiNGYyM2QtODJiNS00NmViLWFhZTYtNGM5Mjk1NDA0YjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDExMzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmRlZDM1MWNmYjhlYjZmMzQ5MDc1MDBmZDlmNjYxM2M4YjkxYzE2NjU3ZTJkNWE0MWJlYWQzNDhiMDBjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7YQ7Y1kQ8NOWj0vcFqpANxRVTBHRqu-q1BgtZYEZegg) The rotation button here is at the top of the selection

what about scaling ? would it be as it is ?

**Comment by CodeDoctorDE** [comment]
Hmm I wouldn't see a problem with this idea. It works on all platforms with touch and mouse and is easy to use

**Comment by Luciogi** [comment]
> Hmm I wouldn't see a problem with this idea. It works on all platforms with touch and mouse and is easy to use

Ok fine

**Comment by CodeDoctorDE** [comment]
Fixed 5 issues today 🎉 Added in 2.1.0-beta.0

**Comment by Luciogi** [comment]
https://github.com/LinwoodDev/Butterfly/assets/84625092/9e58f5c6-b086-4ae6-9772-fbe0375df57a


Follow up bug:
- Select and move, is pushing reference point to rotation handle

**Comment by CodeDoctorDE** [comment]
Hmm, maybe there should be
