### ISSUE TITLE
[Enhancement]: Pens properties should be saved to each

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#610]
### Which feature is your request related to?

Pen Properties

### Describe your request for enhancements!

Currently, changing properties of single pen, applies to all pens

![Screenshot_20240220-150022_Butterfly Nightly](https://github.com/LinwoodDev/Butterfly/assets/84625092/d9ddcee5-ebcd-4c47-99f7-e87a432e01bd)

Each pen should have separate properties saved

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That should already be the case. Can you show me the bug?

**Comment by CodeDoctorDE** [comment]
If you don't know what this dropdown is. This is only for changing the icon in the toolbar for the current pen, it doesn't do anything

**Comment by Luciogi** [comment]
> If you don't know what this dropdown is. This is only for changing the icon in the toolbar for the current pen, it doesn't do anything

Oh I was thinking as it changes actual pen
