### ISSUE TITLE
[Enhancement]: add toggle for color bar

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#611]
### Which feature is your request related to?

Color bar (when pen is selected)

### Describe your request for enhancements!

On small screen, it would be nice to toggle on/off color bar
it would give more page visibility

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, but we can only add this to the color bar. The label toolbar needs to be present

**Comment by Luciogi** [comment]
> Hmm, but we can only add this to the color bar. The label toolbar needs to be present

from my experience assets button(within color bar) is not used frequently, it can be replace with expand/collapse button for color bar

**Comment by CodeDoctorDE** [comment]
It's to select different color palettes.
I would add this to the settings instead of putting a hide button inside the tool

**Comment by Luciogi** [comment]
Umm Another approach(saber notes app uses it) could be adding color tool
Color Tool
- on tap/click shows/hide color bar

**Comment by CodeDoctorDE** [comment]
I'm naming this setting Hide Non-Essential Toolbars and will add it in the personalization setting. Adding another button to the small screen would make it more cluttered

**Comment by CodeDoctorDE** [comment]
I'm naming this setting Hide Non-Essential Toolbars and will add it in the personalization setting. Adding another button to the small screen would make it more cluttered.
The color could also be changed in the tool settings

**Comment by Luciogi** [comment]
i am ready to test implementation

**Comment by CodeDoctorDE** [comment]
added in 2.2.3-rc.0, should be released on 2nd december or just use the webversion https://preview.butterfly.linwood.dev
