### ISSUE TITLE
[Enhancement]: Allow you to save the current state tool position and property as default

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#613]
### Which feature is your request related to?

Tools

### Describe your request for enhancements!

I like to define the position and properties of the pens, eraser etc.. Once it is possible to save it by default for all subsequent documents

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The feature is called Templates. You can create one based on the document when clicking on the top left corner button and then on templates and click on the plus icon

**Comment by CodeDoctorDE** [comment]
Maybe we can rename this feature to "Add template creation dialog" where you can select the tools you need and the backgrounds and it will create the templates for you.

**Comment by CodeDoctorDE** [comment]
I have a new idea. Feel free to vote and comment on this issue what you think: https://github.com/LinwoodDev/Butterfly/discussions/627

**Comment by CodeDoctorDE** [comment]
I added a "Override toolbar" to the templates dialog in 2.1.0-rc.0
