### ISSUE TITLE
[Bug]: Cannot change data directory on android. 

### ISSUE THREAD

**Issue by yotama9** [LinwoodDev/Butterfly#617]
### What happened?

Tapping settings -> data -> data directory results with no response. It should open a file interface to select storage path. 

### Version

2.0.3

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This is a duplicate of #569. The interface I use to select files currently doesn't work on android.
After this is fixed i can reenable this feature.

**Comment by yotama9** [comment]
Damn! I was searching before posting this. But I couldn't find it. Guess we can close this one.

**Comment by CodeDoctorDE** [comment]
Yeah already did it. I will rename this issue to better find it
