### ISSUE TITLE
[Enhancement]:In export SVG: try to reduce file size && improve performance

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#620]
### Which feature is your request related to?

Export svg

### Describe your request for enhancements!

In export SVG:  reduce file size && improve performance

- Join paths together 
- Also try to use css
- decrease decimal points

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi, can you show me a butterfly file that creates a big svg?
It shouldn't be bigger than the butterfly file

**Comment by HusniMuhammad** [comment]
![Screenshot_20240305-151549](https://github.com/LinwoodDev/Butterfly/assets/104101867/1fdf2fa8-2d9b-4b84-8e5b-54fa3482091a)

![Screenshot_20240303-084749](https://github.com/LinwoodDev/Butterfly/assets/104101867/cadc9b5f-0c13-4fa1-91c6-e24995f3f7ef)

**Comment by CodeDoctorDE** [comment]
But is this file really big?
I think i improve the path, I can combine all points into one long path

**Comment by HusniMuhammad** [comment]
Relatively big file size

Also try to reduce decimal points

Btw I'm using this script to faster the  issue  reporting


![IMG_20240305_152453](https://github.com/LinwoodDev/Butterfly/assets/104101867/f19e8c02-90aa-4491-a568-653f8b3c980f)


 Shortcut to Launcher
![export](https://github.com/LinwoodDev/Butterfly/assets/104101867/44342c60-30f6-4737-ba01-010a13db95c1)


Is it ok?

**Comment by CodeDoctorDE** [comment]
I improved the svg export a bit, if you want you can try out: https://butterfly-git-feature-improve-svg-linwood.vercel.app/
(it takes 5 minutes to build)

**Comment by HusniMuhammad** [comment]
![Screenshot_20240305-154813](https://github.com/LinwoodDev/Butterfly/assets/104101867/22d9fc29-4136-4a4e-a1f1-104c198cacaa)
![Screenshot_20240305-154935](https://github.com/LinwoodDev/Butterfly/assets/104101867/40a3d873-63bc-41f3-937c-b5bb115b45d7)
I'm getting random numbers as output file size around 190kb

**Comment by CodeDoctorDE** [comment]
Okay that's the bytes that should be written to the file as binary and not as text xd
Which platform are you on with which os/browser?

**Comment by HusniMuhammad** [comment]
> Okay that's the bytes that should be written to the file as binary and not as text xd Which platform are you on with which os/browser?

![Screenshot_20240305-155526](https://github.com/LinwoodDev/Butterfly/assets/104101867/9d75d246-951b-4f17-b225-ff4066285537)

**Comment by HusniMuhammad** [comment]
Ok that's why character count and byte count are same 😅
![Screenshot_20240305-155905](https://github.com/LinwoodDev/Butterfly/assets/104101867/17286137-c7df-49cb-a4a3-66f1cd15216f)

**Comment by CodeDoctorDE** [comment]
Hmm, i don't know. I get the same problem on web, but not on native platforms.
I will notify you if I have something new

**Comment by HusniMuhammad** [comment]
> Hmm, i don't know. I get the same problem on web, but not on native platforms. I will notify you if I have something new

Ok

**Comment by HusniMuhammad** [comment]
> okay fixed, can you try out?

Ok with the same Link

**Comment by HusniMuhammad** [comment]
Still big though
![Screenshot_20240305-164928](https://github.com/LinwoodDev/Butterfly/assets/104101867/d3ebcc10-f97d-436c-92e1-4167a35ec595)


Reduce decimals

**Comment by HusniMuhammad** [comment]
> > okay fixed, can you try out?
> 
> Ok with the same Link

22kb simple curve

**Comment by CodeDoctorDE** [comment]
Hmm, okay I will try it further

**Comment by HusniMuhammad** [comment]
> Hmm, okay I will try it further

[Tips](https://oreillymedia.github.io/Using_SVG/extras/ch08-precision.html) similar

**Comment by CodeDoctorDE** [comment]
Okay now it should be better. I think I can't smaller the size more

**Comment by HusniMuhammad** [comment]
**ok thanks for the improvement **

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-beta.2
