### ISSUE TITLE
dumm

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#623]
dummy

**Comment by CodeDoctorDE** [comment]
?
Why did you created this issue?

**Comment by CodeDoctorDE** [comment]
Oh okay, I suggest you to create issues using the webinterface, here you have layouts for issues

**Comment by HusniMuhammad** [comment]
> Sorry for the confusion
> 
> I'm testing my emulator ![Screenshot_20240305-232807](https://private-user-images.githubusercontent.com/104101867/310230865-19ed276e-d7de-4c33-81c2-c70e77d0ab82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjE4NTIsIm5iZiI6MTcwOTY2MTU1MiwicGF0aCI6Ii8xMDQxMDE4NjcvMzEwMjMwODY1LTE5ZWQyNzZlLWQ3ZGUtNGMzMy04MWMyLWM3MGU3N2QwYWI4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNzU5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDAzMjcxOWUzMjQ3ZTFhYTNlMGI1MmQzYjIwYWMyZDg5YjIwMjQzMGYxN2FjMjU5NmFhNzEyYzFlNjE2NmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x7521eKSj7LFoJy3qh-vQ0XTRCugOt-qj-K-yDYD6C8)
> 
> Please delete this issue after

For faster reporting

**Comment by HusniMuhammad** [comment]
Web browsers miking my phone xd

**Comment by CodeDoctorDE** [comment]
Hmm, there is also a GitHub app.
Otherwise I they don't add these default labels and headlines for issues

**Comment by HusniMuhammad** [comment]
> Hmm, there is also a GitHub app. Otherwise I they don't add these default labels and headlines for issues

But I can add these labels using scripting

``gh issue label add <label1> <label2> ... --issue <issue-number> --repo <owner/repository>``

**Comment by HusniMuhammad** [comment]
> Hmm, there is also a GitHub app. Otherwise I they don't add these default labels and headlines for issues

I think GitHub app also power 🥛 ing machine

**Comment by CodeDoctorDE** [comment]
Hmm I don't know if this works really because you don't have any permissions on this repo.
I don't know what's the problem. The terminal should also need power to run and if you are at home it shouldn't be a big problem. The layout of the issue layouts needs to be preserved.

**Comment by HusniMuhammad** [comment]
> Hmm I don't know if this works really because you don't have any permissions on this repo. I don't know what's the problem. The terminal should also need power to run and if you are at home it shouldn't be a big problem. The layout of the issue layouts needs to be preserved.


I'm already login into my github command line tool using my own account btw

**Comment by HusniMuhammad** [comment]
Final clarification

Everytime I want report issues

It's will take too much time to do so due low speed and low ram device

Thats why I  going to start using this short of tools

**Comment by CodeDoctorDE** [comment]
Hmm, it's okay if this works otherwise...
Then I will add these labels myself

**Comment by HusniMuhammad** [comment]
> Hmm, it's okay if this works otherwise... Then I will add these labels myself

I can also add label no problem using script ofcourse, I think there's way to preserve issue templates i.e configuring yaml (I forget file extension sorry)

**Comment by HusniMuhammad** [comment]
Here statics:  browsers are power hungry compared to others 
![Screenshot_20240306-000822](https://github.com/LinwoodDev/Butterfly/assets/104101867/702f9bf7-35a8-4f0d-8611-9c9649d2afeb)

**Comment by HusniMuhammad** [comment]
Can I test this issue with proper template included

![Screenshot_20240306-011739](https://github.com/LinwoodDev/Butterfly/assets/104101867/029f48c6-ac8e-4446-b53d-faf05f40b86c)

**Comment by CodeDoctorDE** [comment]
yeah, if you use -l enhancement

**Comment by HusniMuhammad** [comment]
> yeah, if you use -l enhancement

Yes,but  image uploading not supported in GitHub cli :(
