### ISSUE TITLE
[Bug]: Areas exports

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#633]
### What happened?

A bug happened! when I try to export multiple areas to pdf, I can't select areas beyond number 4 due to a bug on the UI
![image](https://github.com/LinwoodDev/Butterfly/assets/47901429/3032b5a3-0641-4735-93f7-36fda6d4d1ee)

### Version

2.1.0-beta.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm, that's out of box design :D

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-beta.3

**Comment by CodeDoctorDE** [comment]
But how should we keep the order?

**Comment by MrGumpIT** [comment]
Keep the order current

**Comment by MrGumpIT** [comment]
in the area select dialog. So I can choose whether to add some pages, but if I want them all I don't have to select them one by one

**Comment by CodeDoctorDE** [comment]
This would help you if we add this button to the empty pdf dialog. 
When we add this to the select you could accidently add them twice

**Comment by MrGumpIT** [comment]
You mean in this window? 
![Screenshot_20240318-233010](https://github.com/LinwoodDev/Butterfly/assets/47901429/8656483d-469f-4d12-a8d6-c39bb8675bd9)
Would be fine
