### ISSUE TITLE
[Bug]: Pdf import create areas and split in page

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#634]
### What happened?

When you try to import a PDF, if you select Create Areas and Split into Pages, the pages are created, the areas are not

### Version

2.1.0-beta.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/9020e80c-7ab6-42c6-8478-053bc2627a3d)
Hmm I can't reproduce it. For me it works but I found another bug that the app doesn't save the current page after importing

**Comment by MrGumpIT** [comment]
https://github.com/LinwoodDev/Butterfly/assets/47901429/32f60006-bb80-4d4a-8505-b94acb39558d

**Comment by CodeDoctorDE** [comment]
The areas view only shows the areas from the current page.
If you split this pdf into different ones, you have an area per page

**Comment by MrGumpIT** [comment]
ok I get it
