### ISSUE TITLE
[Bug]: pdf does not show on canvas after import on Android

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#638]
### What happened?

^

### Version

master branch

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrGumpIT** [comment]
Can you see on setting which version you use?

**Comment by CodeDoctorDE** [comment]
bug not reproducable, did you use the apk build from develop?
You need to click on the position in the canvas where you want to paste the pdf to add it

**Comment by Luciogi** [comment]
> bug not reproducable, did you use the apk build from develop? You need to click on the position in the canvas where you want to paste the pdf to add it

ohh ya pasting works
