### ISSUE TITLE
[Bug]: Lasso tool Acting like Hand when called with stylus button.

### ISSUE THREAD

**Issue by agus-balles** [LinwoodDev/Butterfly#656]
### What happened?

My stylus has a single button and I configured it to call the lasso selection tool but instead of selecting and area when pressed it moves the page around. I found the same behaviour in the pc version(archlinux) when binding the lasso tool to the  right click. I tried both the nightly and stable releases and the bug is present in both.

### Version

2.0.3

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm yeah,
the thing is that the lasso tool has two different types of input. With left click you can select them and with right click you can open the context menu. If you configure changing the tool on right click you will miss one of them.

**Comment by agus-balles** [comment]
And what about the stylus? All the other tools work as expected except for the stylus which acts as the hand.

**Comment by CodeDoctorDE** [comment]
Okay thanks for reporting, I will look into it and try to fix the right click system.
I'm thinking about adding a system that all inputs will be recognized as selection when you change it temporarily with a button

**Comment by agus-balles** [comment]
Thanks, I was searching a note taking app to use with my stylus and stumbled upon  yours and absolutely loved it!.

**Comment by CodeDoctorDE** [comment]
Oh thanks,
why closing it? I will close it after making a fix

**Comment by agus-balles** [comment]
My bad, sorry. Thanks for looking into it

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-beta.4
