### ISSUE TITLE
[Enhancement]: create architecture specific applications for. Android platform 

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#657]
### Describe your request for enhancements!

create architecture specific applications for Android platform like armv7a, armv8a , x86 In GitHub releases

Note:_ F-droid currently not supporting this feature 
So maintain current universal apk design also

If you have resources & time 

Benefit: smaller download size for apk file

Thanks 

### Additional context

I want to download applications faster even though data charges not a problem. for me it's internet speed is the problem Mobile data plan (faster only when midnight 🦇)
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I would add it to the download list if I there is an option to build a architecture specific app.
Do you know if this is possible with flutter and if yes, how?

**Comment by CodeDoctorDE** [comment]
Oh I found something:
```
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --flavor nightly
```
I will try to add it in the next nightly and it should be also available in the next stable 2.1.0

**Comment by CodeDoctorDE** [comment]
Added in 2.1.0-beta.5 or 2.1.0

**Comment by HusniMuhammad** [comment]
> I would add it to the download list if I there is an option to build a architecture specific app. Do you know if this is possible with flutter and if yes, how?

Thanks for replying, I don't have any knowledge about application development in general although I have little bit knowledge in web development and Linux , I think you found solution from yourself, anyway thanks
