### ISSUE TITLE
[Enhancement]: Another toolbar size option small

### ISSUE THREAD

**Issue by HusniMuhammad** [LinwoodDev/Butterfly#659]
### Which feature is your request related to?

Toolbar size in settings

### Describe your request for enhancements!

Decreasing size of toolbar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Already added. Wait for 2.1.0-beta.5.
Now we have
- Tiny
- Small
- Compact
- Normal
- Medium
- Large

**Comment by HusniMuhammad** [comment]
> Already added. Wait for 2.1.0-beta.5. Now we have
> 
> * Tiny
> * Small
> * Compact
> * Normal
> * Medium
> * Large

Ok, thanks ❤️
