### ISSUE TITLE
[Bug]: label tool is not working on nightly builds

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#663]
### What happened?

A bug happened :bug: 

working on stable, but not on nightly

[Screencast_20240413_141032.webm](https://github.com/LinwoodDev/Butterfly/assets/84625092/0600fb2b-3034-4b88-9715-5d0af62c59f2)

### Version

2.1.0-rc.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting! I found this bug yesterday and fixed it again.
Should be fixed in 2.1.0-rc.0
