### ISSUE TITLE
[Enhancement]: add notes file deletion confirmation dialog

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#669]
### Which feature is your request related to?

File management

### Describe your request for enhancements!

It would be nice to have file deletion confirmation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
![grafik](https://github.com/LinwoodDev/Butterfly/assets/20452814/f567fd07-becd-43f5-aa63-a3d0c591290a)
There is already a confirmation or what do you mean?
