### ISSUE TITLE
[Bug]: Exporting image ignores remove background

### ISSUE THREAD

**Issue by oorganic** [LinwoodDev/Butterfly#670]
### What happened?

Because I often have incidents where all of my notes are deleted except my most recent one (something I've discussed in the Matrix chat) I export areas of all of my notes to my files as images.

1) It used to be that when I exported them through "export to" my file managing app it would save under a name I couldn't change but it would be unique. Now, it always saves under the same name (butterfly.png) & gives no warning, so I can overwrite my notes with no awareness or means to stop it unless I make a different folder for each export. This happens regardless of whether the note has a custom name in the app or not.

2) The "don't include background" checkmark no longer does anything, it always exports with a background.

I export as image rather than as PDF because trying to adjust the quality while exporting as PDF (which has the same name issue btw) crashes my entire device if the area is large enough (all of my notes fall into this category) & at 1.00 quality I can't make out the note.

### Version

2.1.0.-beta.5

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting
I have tested it on my samsung device and found this:

1. The export share dialog doesn't allow to save the file really. I don't know what you selected to save it on disk but I couldn't found "Files" or "Download" in the dialog. I'm currently thinking about separated it in "Share" and "Save".
2. this is reproducable, I will fix it for tomorrow.

**Comment by oorganic** [comment]
> Thanks for reporting I have tested it on my samsung device and found this:
> 
>     1. The export share dialog doesn't allow to save the file really. I don't know what you selected to save it on disk but I couldn't found "Files" or "Download" in the dialog. I'm currently thinking about separated it in "Share" and "Save".
> 

Oh, oops, it's not the export option I guess, it's the share option. I share to simple file editor (the orange one from the simple app suite).

**Comment by CodeDoctorDE** [comment]
Hmm, the override is app specific. I don't have this simple file editor, so it would be better to have a "Share" and "Export" button for everyone. Feel free to create a new enhancement issue and I will add it in 2.1.1

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-rc.0
