### ISSUE TITLE
[Enhancement]: Have a "Share" and "Export" button for everyone

### ISSUE THREAD

**Issue by oorganic** [LinwoodDev/Butterfly#672]
### Describe your request for enhancements!

So we can save and manage our notes in our own file managers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
thanks. just want to link #670 here

**Comment by CodeDoctorDE** [comment]
Hmm, I looked a bit and android isn't supported by https://pub.dev/packages/file_selector#features-supported-by-platform. I use https://pub.dev/packages/share_plus for sharing it android and the shareXFiles showed this menu where you couldn't choose your save location

**Comment by CodeDoctorDE** [comment]
Okay, I'm on it. I just code a native implementation for this.
In the future I could implement a library out of it but for now it should work.
I will comment here if I'm finished.

**Comment by CodeDoctorDE** [comment]
I'm finished, can you please test it before I can release this in #673?
Once the build is finished, you can download the builds at the bottom of the page if you are logged in on github: https://github.com/LinwoodDev/Butterfly/actions/runs/8813677196

**Comment by CodeDoctorDE** [comment]
Added in 2.1.0-rc.1
