### ISSUE TITLE
[Bug]: Unable to import PDF or image or other

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#679]
### What happened?

Nothing happens after selecting the file

### Version

v2.1.0-rc.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed. The error message is the euler constant :)

**Comment by MrGumpIT** [comment]
it always comes back 🤣

**Comment by CodeDoctorDE** [comment]
Hi,
I tested it using the add dialog and it works there. Did you use the new open with feature?

**Comment by MrGumpIT** [comment]
I created a new blank note, and then I used Import PDF

**Comment by CodeDoctorDE** [comment]
oh sorry, I just see i fixed it already on develop. should be available on 2.1.0-rc.2
