### ISSUE TITLE
[Feature request]: Only allow strokes to be deleted with path eraser

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#680]
### What happened?

On android and windows, if you import a PDF, then write on it, if you use the Erase Stroke it will also delete the PDF

### Version

v2.1.0-rc.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This is intentional. Should we disable this? Only the normal eraser ignores other elements that are not paths

**Comment by MrGumpIT** [comment]
I think so, it's confusing, when I want to delete a pdf page or an image or whatever, I just select it and delete it

**Comment by CodeDoctorDE** [comment]
I'm currently thinking:
* The normal eraser only erases a part of the path
* The path eraser erases everything it can see

We could make an option to path eraser to only erase path elements and add it to the property view

**Comment by CodeDoctorDE** [comment]
I'm currently thinking:
* The normal eraser only erases a part of the path
* The path eraser erases everything it can see

We could make an option to path eraser to only erase path elements and add it to the property view

**Comment by MrGumpIT** [comment]
I think both should only erase strokes of the pen. anything else labels, PDFs, images can be selected and deleted, it's a common use in apps like this

**Comment by CodeDoctorDE** [comment]
Hmm okay and how should the other elements be removed?

**Comment by MrGumpIT** [comment]
selecting and deleting them

**Comment by CodeDoctorDE** [comment]
I would combine it with #683 and put it in the 2.2 release.
It's a bigger feature and I just want to go forward with it.
Maybe we add an optional feature to include all elements

**Comment by MrGumpIT** [comment]
it could be a solution. in my opinion you should either let the user decide what to delete, adding the icons in the tools, or have the eraser delete only pen strokes (drawings etc.) and let it delete everything else (images, pdfs etc.) using the selection. you choose which approach is best.

**Comment by CodeDoctorDE** [comment]
I think a toolbar is better. If you want to delete multiple things it's easier to use the eraser

**Comment by CodeDoctorDE** [comment]
Added in 2.2.0-beta.0
