### ISSUE TITLE
[Bug]: The template in Backgorund covers the PDF

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#681]
### What happened?

If you import a PDF, and then select a background template, the template will cover the PDF. If you save and close the file and then reopen it, it will work fine. The same happens when you view the grid. The same goes for images. (android/windows)

### Version

v2.1.0-rc.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
bug confirmed, very strange bug

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-rc.2
