### ISSUE TITLE
[Feature request]: Add shape element to normal eraser

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#683]
### What happened?

if you use automatic shape, eraser tool can't delete it 

### Version

all

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
yeah that's intentional since the eraser can only delete paths, and a shape element isn't a path element.
How should the shape look like if you remove a part?

**Comment by CodeDoctorDE** [comment]
Added in 2.2.0-beta.0
