### ISSUE TITLE
[Feature request]: Improve selection tools

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#684]
### Is your feature request related to a problem? Please describe

Use case: When annotating pdf, User writes something on image, and want to delete some strokes, use selections tools like Rectangle selection or lasso , it also selects background and cause its deletion too

### Describe your feature request!

Improve selections tools in such a way that, these only select elements which are inside selected area

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi, thanks for your suggestion.
This could also be related to #680 and #683.
Can we combine this to a solution that this issue is covered?

I'm thinking about adding an option in the lock menu (where you can disable horizontal,  vertical and zoom navigation).
Maybe something like (Select only path)

**Comment by Luciogi** [comment]
Don't you think if you go with (my) above solution, https://github.com/LinwoodDev/Butterfly/issues/680 can be avoided

**Comment by CodeDoctorDE** [comment]
Oh you mean this...
But I think we can also change the selection here too since if the element is only 1 pixel inside, it is inside the area. Sorry I didn't understand the issue on the first read

**Comment by Luciogi** [comment]
> Oh you mean this... But I think we can also change add my idea here too since if the element is only 1 pixel inside, it is inside the area. But i would add your idea too. Sorry I didn't understand the issue on the first read

Yes

**Comment by CodeDoctorDE** [comment]
Added full selection mode in 2.2.0-beta.3 in https://github.com/LinwoodDev/Butterfly/commit/d100fbf0c560964813e3dac143a9e471ba3eb748
