### ISSUE TITLE
[Feature request]: Tool to Lock Elements/Shapes/Strokes

### ISSUE THREAD

**Issue by SoaringSailor** [LinwoodDev/Butterfly#687]
### Is your feature request related to a problem? Please describe

As already stated in #680 #683 and #684 deleting with the different erasers can at times be a bit confusing and annoying as you often delete images or elements you don't want to delete when erasing strokes with the path eraser. Writing on top of PDFs/Images feels a bit frustrating.

### Describe your feature request!

A feature to lock selections might partly fix this problem. For example by having a lock option in the context menu of a selection you could lock the selection so it can't be deleted by any erasers until unlocked. This way you won't be able to erase elements you want to keep around.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm that feels complicated. Additionally when reloading the document it's away.
The layer feature could be the solution here?

**Comment by CodeDoctorDE** [comment]
I think it doesn't make sense here. What about a context menu entry in the selection tool to move all selection to a layer?

**Comment by Widelx** [comment]
Hey ! I'm new to this project. Don't know if I will be contributing much but will follow it. 
What I've seen in some ohter programs (mostly CAO programs) is that depending on the lasso rotation direction you would select only stuff enclosed or touched by it. 
Would it be a good fix ? The only drawback is that user usually don't know about this !

**Comment by CodeDoctorDE** [comment]
Nice, contributions are always welcome.
For selection, there is currently a rectangle and a lasso mode.
What do you mean with lasso rotation? Can you give me an app that uses this method?

**Comment by CodeDoctorDE** [comment]
Hmm,
I'm thinking about it and think this would be overkill:
1. With the group feature, you could also only change the current ones
2. With the new layer idea (see #728) this can also be solved

I think locking a selection would overcomplicate this

**Comment by CodeDoctorDE** [comment]
closing this because of the comment above, feel free to reply
