### ISSUE TITLE
[Feature request]: Option to bind erasers to current layer

### ISSUE THREAD

**Issue by SoaringSailor** [LinwoodDev/Butterfly#688]
### Is your feature request related to a problem? Please describe

This is the a similar problem to #687. 
Writing in a different layer than the inserted pdf and the path eraser still deleting the pdf file does not feel intuitive and is a bit annoying.

### Describe your feature request!

By providing an option to bind the erasers to the current layer this could be prevented. The user could define his own independent and protected layers.

### Additional context

Currently you can already protect different layers from deletion by hiding them first, but I feel like this step should not be necessary.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi, this is a good idea. I would add it to the same lock menu and if you try to select something it also only selects the elements in this layer
