### ISSUE TITLE
[Bug]: the layers are not visible

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#692]
### What happened?

when I create multiple layers (for example 2 layers) if I am on the default layer I can see the drawings of all the layers, if I move to layer 2 I no longer see the drawings of the default layer even if it is checked as visible

### Version

2.1.0-rc.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
bug confirmed, we need to release a 2.1.1.
The release window is currently closed for 2.1.0

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.1-rc.0
