### ISSUE TITLE
[Bug]: imports have bad quality

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#704]
### What happened?

I believe that some changes to the canvas have led to poor quality of the imported files, this happens with both PDFs and images. It is very noticeable when using zoom. It doesn't seem to happen in the stable version, but in the others it does.

### Version

all except stable

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrGumpIT** [comment]
I think the problem is due to the zoom. when I zoom in and out the quality drops dramatically. I don't know if there is a solution.

**Comment by CodeDoctorDE** [comment]
![image](https://github.com/LinwoodDev/Butterfly/assets/20452814/cb5e028c-3da5-4cbe-9aac-c2f27b50b344)
bug reproducable, feel free to create a pr for a fix

**Comment by MrGumpIT** [comment]
how does zoom work, what parts of code should I look at?

**Comment by CodeDoctorDE** [comment]
zoom just changes the state in transformcubit, that will be used inside the paint methods of the image renderers

**Comment by CodeDoctorDE** [comment]
Fixed in #707 by yourself :)
Should land in 2.1.1-rc.1
