### ISSUE TITLE
[Bug]: unable to select .bfly file via import on Android

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#709]
### What happened?

^

https://github.com/LinwoodDev/Butterfly/assets/84625092/fadd6bec-b0e3-4a37-83f9-c337e7532257

### Version

2.1.1-rc.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
thanks for reporting, I can also reproduce it. Another thing I found: When trying to save a bfly, it converts it to a zip

**Comment by CodeDoctorDE** [comment]
fixed in 2.1.1-rc.1
