### ISSUE TITLE
[Bug]: label tool: unable to edit the text inputted 

### ISSUE THREAD

**Issue by Yusei-StarDust** [LinwoodDev/Butterfly#712]
### What happened?

The whole text field will disappear when trying to edit the entered text and click the text field.

### Version

2.1.1-rc.0

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting, bug confirmed

**Comment by CodeDoctorDE** [comment]
thanks, fixed in 2.1.1-rc.1
