### ISSUE TITLE
[Feature request] Multiple file selection

### ISSUE THREAD

**Issue by ShadowZwiebel** [LinwoodDev/Butterfly#713]
### Describe your feature request!

Add the ability to select multible files to perform the same actions with them. Possible actions:
- move
- delete
- copy
- rename with specific pattern. For example numbered from 1 to X

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Added in 2.2.0-rc.0 with 5e618290198433fabf8fa195121f68edc94b382e
