### ISSUE TITLE
[Bug]: Undo Tool removes Zoom Lock

### ISSUE THREAD

**Issue by timonsky** [LinwoodDev/Butterfly#721]
### What happened?

using the undo tool action on stylus input removes activated zoom Lock

https://github.com/LinwoodDev/Butterfly/assets/81168204/f9b1183f-0d1c-42a2-89a5-844515bc915d

### Version

2.1.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
bug confirmed, will be fixed in 2.2.0-beta.0

**Comment by CodeDoctorDE** [comment]
Thanks for reporting, fixed in 2.2.0-beta.0
