### ISSUE TITLE
[Feature request]: Palm Rejection/Pen Only mode

### ISSUE THREAD

**Issue by Redo11** [LinwoodDev/Butterfly#722]
### Is your feature request related to a problem? Please describe

While trying to draw with the pen, my palm get's recognized as an input

### Describe your feature request!

Either a full palm rejection feature or a mode/toggle where only a pen can draw on the canvas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This already exists.
Please note that stylus detection currently does not work on desktop (see #238). You can test it in the behavior settings. There, you can also enable "Pen only input".

**Comment by CodeDoctorDE** [comment]
I will close this for now, feel free to join the discord/matrix or open a github discussion if you need help
