### ISSUE TITLE
[Bug]: Error when changing Data Path to Nextcloud: org.nextcloud.documents is unsupported by this plugin

### ISSUE THREAD

**Issue by Elf3874** [LinwoodDev/Butterfly#734]
### What happened?

When changing the data patch to nextcloud from the side bar, it gives this error:

![Screenshot_20240907-224358](https://github.com/user-attachments/assets/3f1259a7-5294-4f3a-a1a4-09b523fe0ad6)

### Version

2.1.1

### Platform

Android

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I answered on discord already
> Hmm, i don't know much about the android file system but I need a real path that exists on the device to save the documents

You have 2 options to do this:
1. Add a webdav connection inside the app and use this to sync your notes
2. Install the nextcloud app, choose a custom directory on the device and sync this with the app

Feel free to comment here or on discord if you have further questions
