### ISSUE TITLE
[Bug]: rotate and move multiple objects, misalign selections

### ISSUE THREAD

**Issue by Luciogi** [LinwoodDev/Butterfly#742]
### What happened?

1. Draw multiple stroke
2. Select and rotate
3. then move

https://github.com/user-attachments/assets/ecb5c8c0-872a-4a3b-bde2-0040548409d5

### Version

2.2.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yeah looks like #518. I didnt find out the math yet to do this
