### ISSUE TITLE
[Enhancement]: Allow folders with Cyrillic symbols 

### ISSUE THREAD

**Issue by coordinatio** [LinwoodDev/Butterfly#743]
### Which feature is your request related to?

Folder creation

### Describe your request for enhancements!

Thanks for the wonderful software!

It would be so nice if there was an ability to use Cyrillic letters in folder names. Right now it tells "Invalid name" if one tries to create a folder with non-Latin regular symbols.
![Screenshot_20240930_111905](https://github.com/user-attachments/assets/e86bcaba-4390-4041-a75b-9a1860f9a33d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hello, thanks for your issue. For me these looks like latin symbols `Tecm`.
Can you send the symbols here so I can test it myself?

**Comment by coordinatio** [comment]
Sure! Here they are:
```
Тест
```

**Comment by CodeDoctorDE** [comment]
![Screenshot_20240930_111655](https://github.com/user-attachments/assets/67bcff72-ea88-4a23-94e8-4f841591094f)

fixed, should be available in 2.0.1-rc.0 and soon in 2.0.1
