### ISSUE TITLE
[Bug]: Doesn't recognize different inputs from stylus

### ISSUE THREAD

**Issue by Bug-g0** [LinwoodDev/Butterfly#744]
### What happened?

I use butterfly on a Surface go 3 with ubuntu installed. All other applications (such as RNote) correctly manage the eraser input (the back of the pen) and a button I use to activate the select tool. On butterfly all inputs are managed in the same way and I have to manually select the tool I want to to use. With version 2.2 the pressure in the test is always 0.0 even when pressing really hard.

### Version

2.2.0

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Sadly this is a known bug inside the flutter library i use, see #238

**Comment by Bug-g0** [comment]
so no fix?

**Comment by CodeDoctorDE** [comment]
sadly no

**Comment by peperonnii** [comment]
> sadly no

so you *cant* use a stylus with this app?

**Comment by CodeDoctorDE** [comment]
I dont think 🤔 
Flutter doesnt give me the correct input type on desktop but you can test it in the settings
