### ISSUE TITLE
FormatException: Invalid Zip Signature

### ISSUE THREAD

**Issue by lorena130** [LinwoodDev/Butterfly#746]
### What happened?

I can‘t open a file I edited yesterday. And then it was just working fine.
I get this error:
FormatException: Invalid Zip Signature
#0      new ZipFile (package:archive/src/zip/zip_file.dart:52)
#1      ZipFileHeader.readLocalFileHeader (package:archive/src/zip/zip_file_header.dart:104)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:63)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:24)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:16)
#5      noteDataMigrator (package:butterfly_api/src/converter/note.dart:16)
#6      new NoteData.fromData (package:butterfly_api/src/models/data.dart:47)
#7      _decode (package:butterfly/api/file_system.dart:16)
#8      TypedDirectoryFileSystem._toTypedAsset (package:lw_file_system/src/api/typed.dart:78)
#9      TypedDirectoryFileSystem.readAsset.<anonymous closure> (package:lw_file_system/src/api/typed.dart:117)
<asynchronous suspension>
#10     GeneralDirectoryFileSystem.fetchAsset (package:lw_file_system/src/api/base/directory.dart:25)
<asynchronous suspension>
#11     Stream.last.<anonymous closure> (dart:async/stream.dart:1607)
<asynchronous suspension>
#12     _ProjectPageState._load (package:butterfly/views/main.dart:210)
<asynchronous suspension>

### Version

2.2.0

### Platform

Windows

### Relevant log output

```shell
#0      new ZipFile (package:archive/src/zip/zip_file.dart:52)
#1      ZipFileHeader.readLocalFileHeader (package:archive/src/zip/zip_file_header.dart:104)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:63)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:24)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:16)
#5      noteDataMigrator (package:butterfly_api/src/converter/note.dart:16)
#6      new NoteData.fromData (package:butterfly_api/src/models/data.dart:47)
#7      _decode (package:butterfly/api/file_system.dart:16)
#8      TypedDirectoryFileSystem._toTypedAsset (package:lw_file_system/src/api/typed.dart:78)
#9      TypedDirectoryFileSystem.readAsset.<anonymous closure> (package:lw_file_system/src/api/typed.dart:117)
<asynchronous suspension>
#10     GeneralDirectoryFileSystem.fetchAsset (package:lw_file_system/src/api/base/directory.dart:25)
<asynchronous suspension>
#11     Stream.last.<anonymous closure> (dart:async/stream.dart:1607)
<asynchronous suspension>
#12     _ProjectPageState._load (package:butterfly/views/main.dart:210)
<asynchronous suspension>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm looks like the file got corrupted. Can you try exporting the data and sending it? (You can use the direct message on discord or matrix if you want to send it privately)

**Comment by lorena130** [comment]
[Mathe Schul_bung.zip](https://github.com/user-attachments/files/17257418/Mathe.Schul_bung.zip)
I hope this isthe I hope this is the right Format.

**Comment by CodeDoctorDE** [comment]
hmm looks really like an archive corruption. I don't really know how I could fix this...
The page file couldn't be read here...

**Comment by CodeDoctorDE** [comment]
i cannot find any problems. seems like the app is crashed or was in an invalid state. feel free to find a way that i can reproduce it, for now i don't see any problems on my side
