### ISSUE TITLE
[Bug]: Android: Different data location doesn't seem to work

### ISSUE THREAD

**Issue by pcause** [LinwoodDev/Butterfly#747]
### What happened?

I started the app, clicked settings and chose a location in my file system to use.  I create a folder and then a note.  When I look at the file system after closing the app, the folder is there but the note within it is no there.  I open the app and can access the note and the name has the folder/nameigavethenote displayed.

Also, where is "default path"?

### Version

2.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
See #569.
The default path is in Android/data/dev.linwood.butterfly
