### ISSUE TITLE
[Bug]: notes disappear on Android

### ISSUE THREAD

**Issue by coordinatio** [LinwoodDev/Butterfly#749]
### What happened?

In a sudden, when I opened the application, one of the notes disappeared. I was still able to see the note's file in file system using file explorer, but the note was missing in the Butterfly's note explorer. I've tried to re-setup data directory in settings in a hope that that will force the app to re-read the file system, but that did not help. I've ended with recovering the whole directory from a backup made with Syncthing. Now I have all the files in place, and I can open them from a file explorer one-by-one using Butterfly, but I still can not see the files inside the Buttrefly's file explorer. It shows only directories with no notes inside.

### Version

2.2.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
There are currently some issues regarding custom data directories that will be fixed in the next nightly next monday, then i will publish a new stable once everything has been solved, see #562

**Comment by CodeDoctorDE** [comment]
This should now be fixed in 2.2.1

**Comment by Wikinaut** [comment]
![Screenshot_20241110_194751.png](https://github.com/user-attachments/assets/69ea13fb-8c28-48cc-a063-51539edfa641)

* Butterfly version  2.2.1-rc.2 
* Android 14
* Samsung A54

Selection of an export directory on internal or external memory (SD card) or Nextcloud directory folder does **not** work and therefore export does not work for me. I cannot access files in /Android/data/* - apparently for security reasons of Android 14.

Creation of a new folder works.

**Comment by CodeDoctorDE** [comment]
Hello, it would be nice if you could open a separate issue.
I'm currently not really sure what you mean. Did it show the error when selecting the path?
Is this showing when opening the app? Will it create the Documents, Templates, Packs subdirectory in this path?
Sadly nextcloud doesn't work since it only allows local directories. Android/data is an android restriction I sadly cannot change.
