### ISSUE TITLE
Bug: Pages Feature Broken

### ISSUE THREAD

**Issue by hanmalman** [LinwoodDev/Butterfly#755]
If i create a new page a new page is created i can write on it but when trying going back to page 1 the content of page 2 is the one that is displayed if i create a new page is blank again if write on it and try to go back to the others the content in page 3 is displayed in 1 and 2, what i wrote in page 1 and 2 is lost forever.

On Android 12, Fdroid version

**Comment by CodeDoctorDE** [comment]
thanks for reporting, I can reproduce this.
Next time, feel free to write which version you use (Settings -> General -> Current version).

**Comment by CodeDoctorDE** [comment]
fixed in 2.2.2-rc.1
