### ISSUE TITLE
[Enhancement]: Always visible save button

### ISSUE THREAD

**Issue by maarriaa** [LinwoodDev/Butterfly#757]
### Is your feature request related to a problem? Please describe

I have experienced multiple times the loss of work after closing the Butterfly app. Despite having autosave enabled, the last modifications were not consistently saved when closing and reopening the app. This unreliable saving mechanism creates potential data loss. A manual save button that is always visible would provide users with an additional layer of control, allowing them to explicitly save their progress before exiting the app and mitigate the risk of losing important work, even when the autosave feature is active.

### Describe your feature request!

- save button always visible in the app interface (even when autosave is on)
- provides immediate visual feedback when changes are saved (e.g. a brief message)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi, thanks for reporting. This is already possible, go to settings -> behaviors -> autosave and turn it off.
If you have reproducable steps how to reproduce the data loss, feel free to report it too. Then I could fix this too.

**Comment by maarriaa** [comment]
Thank you for the answer. I know that the save button appears when the autosave is off. My feature request was specifically to have the manual save button visible and accessible at all times, even when autosave is enabled for the extra piece of mind. Right now, the save button only shows up if autosave is off.

**Comment by CodeDoctorDE** [comment]
Okay, I could add it maybe as three state setting:
Autosave:
- On
- On, but button is visible
- Off

**Comment by maarriaa** [comment]
That sounds good!

**Comment by CodeDoctorDE** [comment]
roadmap changed and issue is now classified as enhancement (small feature that can be added to a minor release).
Should be released in the next nightly and stable release (maybe in 2-3 weeks).

**Comment by CodeDoctorDE** [comment]
added in 2.2.3-rc.0
