### ISSUE TITLE
[Bug]: line width changing with zoom level

### ISSUE THREAD

**Issue by timkrief** [LinwoodDev/Butterfly#765]
### What happened?

A bug happened!

Hi,

I tried the standard pen with different zoom levels and it had different line width. At first I thought that it was intentional so that the line width would be the same from the screen size perspective, but even then it's not the same line width from that perspective. It's way bigger when zoomed out than when zoomed in.

I was using latest fdroid release.

### Version

2.2.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's intentional. You write down bigger if you zoom out to have the same stroke width.
But I can see that this is not the ideal "default" state. Next release i will try to change this and maybe make a "First time setup" page for that

**Comment by timkrief** [comment]
Yes, I know, as I said

> At first I thought that it was intentional so that the line width would be the same from the screen size perspective, but even then it's not the same line width from that perspective. 

Here's a video to show what I mean

https://github.com/user-attachments/assets/0d4589a7-dd7c-49dc-8c1b-90ecae886148

line width gets bigger and bigger (bigger than the intended effect)

**Comment by CodeDoctorDE** [comment]
found the problem, fixed it. should be available 2.2.3-rc.1 and in the next stable 2.2.3

**Comment by CodeDoctorDE** [comment]
yeah, you can see it in the commit: https://github.com/LinwoodDev/Butterfly/commit/780e1495fe293569034af829e07e045ae9b6a897#diff-181e082a029dd07f1770bc4e3b6345f7796f4d973d7a64ea57a1da4b8f0eb87aR109

I divided the stroke width for the whole element + the divided the pressure on the point itself.
I removed the one on the point so it only contributes one time

**Comment by timkrief** [comment]
Oh so it might also fix the weird artifact at the beginning of the stroke too. 🤔

**Comment by CodeDoctorDE** [comment]
This happens if you have a too big stroke width and a too small stroke, you could also play with the properties of the tool to fix it partially
